/*
 * dtk reversed-extab group `auto_fn_800A8F4C_text` bundle (1 TU, indivisible).
 * Held as asm_fn with manually emitted extab/extabindex via __declspec(section ".extab_user"/".extabindex_user"). tools/postprocess_extab_user.py renames sections + symbols to the
 * extab/extabindex + @etb_/@eti_ form dtk expects.
 *
 * Phase 3a/3b probe: all fns held as asm_fn initially, promote 1 fn at a
 * time via sub-agent dispatch (asm_fn -> matched).
 *
 * Generated by `python tools/scaffold_mega_bundle.py --group auto_fn_800A8F4C_text`.
 * Re-run to regenerate; hand edits below this header may be overwritten.
 *
 * See docs/per_fn_matching_strategy.md and docs/large_extab_group_strategy.md.
 */

/* === extracted from auto_fn_800A8F4C_text === */
/* Copy into the TU between forward decls and function bodies; */
/* keep emit order = target section layout (do not sort). */

/* --- extern decls: branch callees (bl/b targets) --- */
/* Open prototype (`extern void Foo();`) accepts any call signature; */
/* refine if the real prototype matters for header consumers. */
extern void Alloc();
extern void DebugPrintf();
extern void WarpDashMgr_Init();
extern void MemoryManager_TimedFree(void *);
extern void dtor_800AA69C(void *, short);
extern void fn_80270CF4();
extern void fn_80270D6C();
extern void fn_8027E480();
extern void fn_8027E9E8();

/* --- extern decls: sda21-referenced data --- */
extern unsigned int lbl_806D4DE8;
extern unsigned int lbl_806D4DEC;
extern unsigned int lbl_806D4DF0;
extern unsigned int lbl_806D4DF4;
extern unsigned int lbl_806D4DF8;
extern unsigned int lbl_806D4DFC;
extern unsigned int lbl_806D4E00;
extern unsigned int lbl_806D4E08;
extern unsigned int lbl_806D4E10;
extern unsigned int lbl_806D4E18;
extern const float lbl_806D4E1C;
extern unsigned int lbl_806D4E20;

/* WarpDashMgr instance array: lbl_806CF238 (sdata, size 0x8 = 2 entries). */
/* Indexed by `(u8)id != 0` -> 0 or 1, so a 2-element pointer array fits the */
/* sda21 1-instr base load that the bundle relies on. */
extern void *lbl_806CF238[2];

/* --- extern decls: large-data refs (@ha/@l pairs) --- */
/* Open array (`[]`) avoids sda21 strict-mode link errors when a future */
/* promote rewrites the asm_fn to C and references the symbol as `arr[i]`. */
extern unsigned int dtor_80036E40[];
extern unsigned int fn_8007C5DC[];
extern unsigned int lbl_80328468[];
extern unsigned int lbl_80328474[];
extern unsigned int lbl_80328480[];

/* --- forward decls --- */
asm void WarpZone_FindContainingOBB(void);
asm void WarpZone_CalcExitPosition(void);
asm void WarpZone_FindContaining(void);
asm void WarpDashMgr_Cleanup(void);
void *WarpDashMgr_GetInstance(unsigned char id);
asm void WarpDashMgr_GetOrCreate(void);
asm void Free_IfOwnedShort(void);
asm void WarpAutoRun_Init(void);
asm void DashZone_ProcessAutoRun(void);
asm void WarpAutoRun_GetParam(void);
void WarpAutoRun_OnEnter(void *self, float f1, float f2, float f3, float f4, float vx, float vy, float vz);
asm void WarpZone_CheckEntry(void);
asm void Field4NotMinusOne(void);
asm void WarpZone_CalcEdgeVectors(void);
void *dtor_800A9CC8(void *this, short flag);
void *dtor_800A9D2C(void *this, short flag);

/* --- extab (manual emit, .extab_user -> extab via objcopy) --- */
/* dtor_800A9CC8 promoted to C; CW auto-emits its extab/extabindex. */
#pragma section R ".extab_user"
__declspec(section ".extab_user") static const unsigned char extab_dtor_800A9D2C[8] = {
    0x10, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_fn_800A8F4C[8] = {
    0x00, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_WarpZone_CalcExitPosition[8] = {
    0x00, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_WarpZone_FindContaining[8] = {
    0x00, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_WarpDashMgr_Cleanup[8] = {
    0x20, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const struct { unsigned int f0; unsigned int f1; unsigned int f2; unsigned int f3; unsigned int f4; void *f5; } extab_WarpDashMgr_GetOrCreate = { 0x38080000, 0x00000064, 0x00000010, 0x00000000, 0x8A800019, (void *)&MemoryManager_TimedFree };
__declspec(section ".extab_user") static const unsigned char extab_fn_800A9414[8] = {
    0x08, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_DashZone_ProcessAutoRun[8] = {
    0x08, 0x4A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_WarpAutoRun_GetParam[8] = {
    0x28, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_WarpZone_CheckEntry[8] = {
    0x00, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_WarpZone_CalcEdgeVectors[8] = {
    0x08, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

/* --- extabindex (manual emit, .extabindex_user -> extabindex via objcopy) --- */
#pragma section R ".extabindex_user"
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_fn_800A8F4C = {
    (void *)&WarpZone_FindContainingOBB, 0x00000138, (void *)extab_fn_800A8F4C
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_WarpZone_CalcExitPosition = {
    (void *)&WarpZone_CalcExitPosition, 0x00000118, (void *)extab_WarpZone_CalcExitPosition
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_WarpZone_FindContaining = {
    (void *)&WarpZone_FindContaining, 0x00000138, (void *)extab_WarpZone_FindContaining
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_WarpDashMgr_Cleanup = {
    (void *)&WarpDashMgr_Cleanup, 0x000000A4, (void *)extab_WarpDashMgr_Cleanup
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_WarpDashMgr_GetOrCreate = {
    (void *)&WarpDashMgr_GetOrCreate, 0x00000080, (void *)&extab_WarpDashMgr_GetOrCreate
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_fn_800A9414 = {
    (void *)&Free_IfOwnedShort, 0x0000003C, (void *)extab_fn_800A9414
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_DashZone_ProcessAutoRun = {
    (void *)&DashZone_ProcessAutoRun, 0x000001E0, (void *)extab_DashZone_ProcessAutoRun
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_WarpAutoRun_GetParam = {
    (void *)&WarpAutoRun_GetParam, 0x000001A0, (void *)extab_WarpAutoRun_GetParam
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_WarpZone_CheckEntry = {
    (void *)&WarpZone_CheckEntry, 0x00000170, (void *)extab_WarpZone_CheckEntry
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_WarpZone_CalcEdgeVectors = {
    (void *)&WarpZone_CalcEdgeVectors, 0x00000324, (void *)extab_WarpZone_CalcEdgeVectors
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_dtor_800A9D2C = {
    (void *)&dtor_800A9D2C, 0x00000058, (void *)extab_dtor_800A9D2C
};

/* --- asm function bodies (.text order = fn address order) --- */
asm void WarpZone_FindContainingOBB(void) {
    nofralloc
    stwu r1, -0x20(r1)
    lbz r0, 0x18(r3)
    cmplwi r0, 0x0
    bne fn_800A8F4C_L_800A8F64
    li r3, -0x1
    b fn_800A8F4C_L_800A907C
    fn_800A8F4C_L_800A8F64:
    lwz r0, 0x10(r3)
    cmpwi r0, 0x0
    bgt fn_800A8F4C_L_800A8F78
    li r3, -0x1
    b fn_800A8F4C_L_800A907C
    fn_800A8F4C_L_800A8F78:
    frsp f5, f3
    stfs f1, 0x8(r1)
    frsp f6, f1
    lfs f4, lbl_806D4DE8(r2)
    stfs f2, 0xc(r1)
    li r7, 0x0
    stfs f3, 0x10(r1)
    li r4, 0x0
    mtctr r0
    ble fn_800A8F4C_L_800A9078
    fn_800A8F4C_L_800A8FA0:
    lwz r0, 0x14(r3)
    add r5, r0, r4
    lwz r6, 0x0(r5)
    lfs f0, 0xc(r5)
    lfs f1, 0xc(r6)
    lfs f2, 0x14(r6)
    fsubs f3, f6, f1
    lfs f1, 0x4(r5)
    fsubs f2, f5, f2
    fmuls f0, f3, f0
    fneg f2, f2
    fmadds f0, f2, f1, f0
    fcmpo cr0, f0, f4
    ble fn_800A8F4C_L_800A8FE0
    li r0, 0x0
    b fn_800A8F4C_L_800A9058
    fn_800A8F4C_L_800A8FE0:
    lfs f0, 0x18(r5)
    lfs f1, 0x10(r5)
    fmuls f0, f3, f0
    fmadds f0, f2, f1, f0
    fcmpo cr0, f0, f4
    ble fn_800A8F4C_L_800A9000
    li r0, 0x0
    b fn_800A8F4C_L_800A9058
    fn_800A8F4C_L_800A9000:
    lfs f0, 0x24(r6)
    lfs f1, 0x2c(r6)
    fsubs f3, f6, f0
    lfs f0, 0x24(r5)
    fsubs f2, f5, f1
    lfs f1, 0x1c(r5)
    fmuls f0, f3, f0
    fneg f2, f2
    fmadds f0, f2, f1, f0
    fcmpo cr0, f0, f4
    ble fn_800A8F4C_L_800A9034
    li r0, 0x0
    b fn_800A8F4C_L_800A9058
    fn_800A8F4C_L_800A9034:
    lfs f0, 0x30(r5)
    lfs f1, 0x28(r5)
    fmuls f0, f3, f0
    fmadds f0, f2, f1, f0
    fcmpo cr0, f0, f4
    ble fn_800A8F4C_L_800A9054
    li r0, 0x0
    b fn_800A8F4C_L_800A9058
    fn_800A8F4C_L_800A9054:
    li r0, 0x1
    fn_800A8F4C_L_800A9058:
    clrlwi r0, r0, 24
    cmplwi r0, 0x1
    bne fn_800A8F4C_L_800A906C
    mr r3, r7
    b fn_800A8F4C_L_800A907C
    fn_800A8F4C_L_800A906C:
    addi r7, r7, 0x1
    addi r4, r4, 0x50
    bdnz fn_800A8F4C_L_800A8FA0
    fn_800A8F4C_L_800A9078:
    li r3, -0x1
    fn_800A8F4C_L_800A907C:
    addi r1, r1, 0x20
    blr
}

asm void WarpZone_CalcExitPosition(void) {
    nofralloc
    stwu r1, -0x20(r1)
    mflr r0
    stw r0, 0x24(r1)
    lbz r0, 0x18(r3)
    cmplwi r0, 0x0
    beq WarpZone_CalcExitPosition_L_800A918C
    cmpwi r4, -0x1
    bne WarpZone_CalcExitPosition_L_800A90B8
    lis r3, lbl_80328474@ha
    addi r3, r3, lbl_80328474@l
    crxor 6, 6, 6
    bl DebugPrintf
    b WarpZone_CalcExitPosition_L_800A918C
    WarpZone_CalcExitPosition_L_800A90B8:
    mulli r0, r4, 0x50
    lwz r3, 0x8(r3)
    frsp f5, f1
    stfs f1, 0x8(r1)
    frsp f7, f2
    add r4, r3, r0
    lwz r3, 0x0(r4)
    frsp f6, f3
    lfs f1, 0x40(r4)
    lfs f4, 0x0(r3)
    lfs f0, 0x4(r3)
    fsubs f8, f5, f4
    lfs f5, 0x8(r3)
    lfs f4, 0x34(r4)
    fsubs f7, f7, f0
    lfs f0, 0x38(r4)
    fsubs f6, f6, f5
    lfs f5, 0x3c(r4)
    fmuls f4, f8, f4
    fmuls f0, f7, f0
    lfs f10, 0x48(r4)
    fmuls f5, f6, f5
    lfs f9, 0x44(r4)
    stfs f2, 0xc(r1)
    fadds f2, f4, f0
    stfs f3, 0x10(r1)
    lfs f0, 0x30(r3)
    fadds f4, f5, f2
    stfs f1, 0x14(r1)
    stfs f9, 0x18(r1)
    fmuls f3, f1, f4
    fmuls f2, f9, f4
    stfs f10, 0x1c(r1)
    fmuls f1, f10, f4
    fadds f0, f3, f0
    stfs f8, 0x8(r1)
    stfs f7, 0xc(r1)
    stfs f0, 0x0(r5)
    lwz r3, 0x0(r4)
    stfs f6, 0x10(r1)
    lfs f0, 0x34(r3)
    stfs f3, 0x14(r1)
    fadds f0, f2, f0
    stfs f2, 0x18(r1)
    stfs f0, 0x0(r6)
    lwz r3, 0x0(r4)
    stfs f1, 0x1c(r1)
    lfs f0, 0x38(r3)
    fadds f0, f1, f0
    stfs f0, 0x0(r7)
    lwz r3, 0x0(r4)
    lfs f0, 0x48(r3)
    stfs f0, 0x0(r8)
    WarpZone_CalcExitPosition_L_800A918C:
    lwz r0, 0x24(r1)
    mtlr r0
    addi r1, r1, 0x20
    blr
}

asm void WarpZone_FindContaining(void) {
    nofralloc
    stwu r1, -0x20(r1)
    lbz r0, 0x18(r3)
    cmplwi r0, 0x0
    bne WarpZone_FindContaining_L_800A91B4
    li r3, -0x1
    b WarpZone_FindContaining_L_800A92CC
    WarpZone_FindContaining_L_800A91B4:
    lwz r0, 0x4(r3)
    cmpwi r0, 0x0
    bgt WarpZone_FindContaining_L_800A91C8
    li r3, -0x1
    b WarpZone_FindContaining_L_800A92CC
    WarpZone_FindContaining_L_800A91C8:
    frsp f5, f3
    stfs f1, 0x8(r1)
    frsp f6, f1
    lfs f4, lbl_806D4DE8(r2)
    stfs f2, 0xc(r1)
    li r7, 0x0
    stfs f3, 0x10(r1)
    li r4, 0x0
    mtctr r0
    ble WarpZone_FindContaining_L_800A92C8
    WarpZone_FindContaining_L_800A91F0:
    lwz r0, 0x8(r3)
    add r5, r0, r4
    lwz r6, 0x0(r5)
    lfs f0, 0xc(r5)
    lfs f1, 0xc(r6)
    lfs f2, 0x14(r6)
    fsubs f3, f6, f1
    lfs f1, 0x4(r5)
    fsubs f2, f5, f2
    fmuls f0, f3, f0
    fneg f2, f2
    fmadds f0, f2, f1, f0
    fcmpo cr0, f0, f4
    ble WarpZone_FindContaining_L_800A9230
    li r0, 0x0
    b WarpZone_FindContaining_L_800A92A8
    WarpZone_FindContaining_L_800A9230:
    lfs f0, 0x18(r5)
    lfs f1, 0x10(r5)
    fmuls f0, f3, f0
    fmadds f0, f2, f1, f0
    fcmpo cr0, f0, f4
    ble WarpZone_FindContaining_L_800A9250
    li r0, 0x0
    b WarpZone_FindContaining_L_800A92A8
    WarpZone_FindContaining_L_800A9250:
    lfs f0, 0x24(r6)
    lfs f1, 0x2c(r6)
    fsubs f3, f6, f0
    lfs f0, 0x24(r5)
    fsubs f2, f5, f1
    lfs f1, 0x1c(r5)
    fmuls f0, f3, f0
    fneg f2, f2
    fmadds f0, f2, f1, f0
    fcmpo cr0, f0, f4
    ble WarpZone_FindContaining_L_800A9284
    li r0, 0x0
    b WarpZone_FindContaining_L_800A92A8
    WarpZone_FindContaining_L_800A9284:
    lfs f0, 0x30(r5)
    lfs f1, 0x28(r5)
    fmuls f0, f3, f0
    fmadds f0, f2, f1, f0
    fcmpo cr0, f0, f4
    ble WarpZone_FindContaining_L_800A92A4
    li r0, 0x0
    b WarpZone_FindContaining_L_800A92A8
    WarpZone_FindContaining_L_800A92A4:
    li r0, 0x1
    WarpZone_FindContaining_L_800A92A8:
    clrlwi r0, r0, 24
    cmplwi r0, 0x1
    bne WarpZone_FindContaining_L_800A92BC
    mr r3, r7
    b WarpZone_FindContaining_L_800A92CC
    WarpZone_FindContaining_L_800A92BC:
    addi r7, r7, 0x1
    addi r4, r4, 0x50
    bdnz WarpZone_FindContaining_L_800A91F0
    WarpZone_FindContaining_L_800A92C8:
    li r3, -0x1
    WarpZone_FindContaining_L_800A92CC:
    addi r1, r1, 0x20
    blr
}

asm void WarpDashMgr_Cleanup(void) {
    nofralloc
    stwu r1, -0x20(r1)
    mflr r0
    stw r0, 0x24(r1)
    stw r31, 0x1c(r1)
    li r31, 0x0
    stw r30, 0x18(r1)
    stw r29, 0x14(r1)
    addi r29, r13, -0x7AE8  /* lbl_806CF238 */
    stw r28, 0x10(r1)
    li r28, 0x0
    WarpDashMgr_Cleanup_L_800A92FC:
    lwz r30, 0x0(r29)
    cmplwi r30, 0x0
    beq WarpDashMgr_Cleanup_L_800A9344
    addic. r0, r30, 0xc
    beq WarpDashMgr_Cleanup_L_800A9324
    addic. r0, r30, 0xc
    beq WarpDashMgr_Cleanup_L_800A9324
    addi r3, r30, 0xc
    li r4, 0x0
    bl dtor_800AA69C
    WarpDashMgr_Cleanup_L_800A9324:
    cmplwi r30, 0x0
    beq WarpDashMgr_Cleanup_L_800A933C
    beq WarpDashMgr_Cleanup_L_800A933C
    mr r3, r30
    li r4, 0x0
    bl dtor_800AA69C
    WarpDashMgr_Cleanup_L_800A933C:
    mr r3, r30
    bl MemoryManager_TimedFree
    WarpDashMgr_Cleanup_L_800A9344:
    addi r28, r28, 0x1
    stw r31, 0x0(r29)
    cmpwi r28, 0x2
    addi r29, r29, 0x4
    blt WarpDashMgr_Cleanup_L_800A92FC
    lwz r0, 0x24(r1)
    lwz r31, 0x1c(r1)
    lwz r30, 0x18(r1)
    lwz r29, 0x14(r1)
    lwz r28, 0x10(r1)
    mtlr r0
    addi r1, r1, 0x20
    blr
}

void *WarpDashMgr_GetInstance(unsigned char id) {
    return lbl_806CF238[id != 0];
}

asm void WarpDashMgr_GetOrCreate(void) {
    nofralloc
    stwu r1, -0x30(r1)
    mflr r0
    stw r0, 0x34(r1)
    stmw r25, 0x14(r1)
    mr r29, r6
    clrlwi r6, r6, 24
    addi r30, r13, -0x7AE8  /* lbl_806CF238 */
    neg r0, r6
    mr r26, r3
    or r0, r0, r6
    mr r27, r4
    rlwinm r31, r0, 3, 29, 29
    mr r28, r5
    lwzx r0, r30, r31
    cmplwi r0, 0x0
    bne WarpDashMgr_GetOrCreate_L_800A93FC
    li r3, 0x1c
    bl Alloc
    mr. r25, r3
    beq WarpDashMgr_GetOrCreate_L_800A93F8
    mr r4, r26
    mr r5, r27
    mr r6, r28
    mr r7, r29
    bl WarpDashMgr_Init
    WarpDashMgr_GetOrCreate_L_800A93F8:
    stwx r25, r30, r31
    WarpDashMgr_GetOrCreate_L_800A93FC:
    lwzx r3, r30, r31
    lmw r25, 0x14(r1)
    lwz r0, 0x34(r1)
    mtlr r0
    addi r1, r1, 0x30
    blr
}

asm void Free_IfOwnedShort(void) {
    nofralloc
    stwu r1, -0x10(r1)
    mflr r0
    stw r0, 0x14(r1)
    stw r31, 0xc(r1)
    mr. r31, r3
    beq fn_800A9414_L_800A9438
    extsh. r0, r4
    ble fn_800A9414_L_800A9438
    bl MemoryManager_TimedFree
    fn_800A9414_L_800A9438:
    lwz r0, 0x14(r1)
    mr r3, r31
    lwz r31, 0xc(r1)
    mtlr r0
    addi r1, r1, 0x10
    blr
}

asm void WarpAutoRun_Init(void) {
    nofralloc
    li r0, 0x0
    lfs f0, lbl_806D4DE8(r2)
    stw r0, 0x0(r3)
    li r0, -0x1
    stw r0, 0x4(r3)
    stfs f0, 0x8(r3)
    stb r4, 0x20(r3)
    stfs f0, 0x14(r3)
    stfs f0, 0x18(r3)
    stfs f0, 0x1c(r3)
    blr
}

asm void DashZone_ProcessAutoRun(void) {
    nofralloc
    stwu r1, -0x20(r1)
    mflr r0
    stw r0, 0x24(r1)
    stfd f31, 0x10(r1)
    psq_st f31, 0x18(r1), 0, 0
    stw r31, 0xc(r1)
    mr r31, r3
    addi r3, r13, -0x7AE8  /* lbl_806CF238 */
    lbz r4, 0x20(r31)
    fmr f31, f4
    neg r0, r4
    or r0, r0, r4
    rlwinm r0, r0, 3, 29, 29
    lwzx r4, r3, r0
    cmplwi r4, 0x0
    beq DashZone_ProcessAutoRun_L_800A94DC
    lfs f1, 0x8(r31)
    lfs f0, lbl_806D4DE8(r2)
    fcmpo cr0, f1, f0
    cror eq, lt, eq
    beq DashZone_ProcessAutoRun_L_800A94DC
    lwz r0, 0x4(r31)
    cmpwi r0, -0x1
    bne DashZone_ProcessAutoRun_L_800A9514
    DashZone_ProcessAutoRun_L_800A94DC:
    lfs f0, lbl_806D4DE8(r2)
    stfs f0, 0x14(r31)
    stfs f0, 0x18(r31)
    stfs f0, 0x1c(r31)
    lwz r0, 0x0(r31)
    cmpwi r0, 0x1
    bne DashZone_ProcessAutoRun_L_800A9504
    li r0, 0x2
    stw r0, 0x0(r31)
    b DashZone_ProcessAutoRun_L_800A950C
    DashZone_ProcessAutoRun_L_800A9504:
    li r0, 0x0
    stw r0, 0x0(r31)
    DashZone_ProcessAutoRun_L_800A950C:
    lwz r3, 0x0(r31)
    b DashZone_ProcessAutoRun_L_800A9640
    DashZone_ProcessAutoRun_L_800A9514:
    lfs f0, lbl_806D4DEC(r2)
    fsubs f0, f1, f0
    stfs f0, 0x8(r31)
    lbz r0, 0x18(r4)
    lwz r3, 0x4(r31)
    cmplwi r0, 0x0
    beq DashZone_ProcessAutoRun_L_800A9560
    cmpwi r3, -0x1
    bne DashZone_ProcessAutoRun_L_800A954C
    lis r3, lbl_80328468@ha
    addi r3, r3, lbl_80328468@l
    crxor 6, 6, 6
    bl DebugPrintf
    b DashZone_ProcessAutoRun_L_800A9560
    DashZone_ProcessAutoRun_L_800A954C:
    mulli r0, r3, 0x50
    lwz r3, 0x14(r4)
    lwzx r3, r3, r0
    lfs f0, 0x48(r3)
    stfs f0, 0xc(r31)
    DashZone_ProcessAutoRun_L_800A9560:
    lfs f1, lbl_806D4DE8(r2)
    fmr f3, f31
    lfs f0, 0xc(r31)
    fcmpo cr0, f31, f1
    stfs f0, 0x10(r31)
    ble DashZone_ProcessAutoRun_L_800A9594
    lfs f0, lbl_806D4DF0(r2)
    b DashZone_ProcessAutoRun_L_800A9584
    DashZone_ProcessAutoRun_L_800A9580:
    fsubs f3, f3, f0
    DashZone_ProcessAutoRun_L_800A9584:
    fcmpo cr0, f3, f0
    cror eq, gt, eq
    beq DashZone_ProcessAutoRun_L_800A9580
    b DashZone_ProcessAutoRun_L_800A95AC
    DashZone_ProcessAutoRun_L_800A9594:
    bge DashZone_ProcessAutoRun_L_800A95AC
    lfs f0, lbl_806D4DF0(r2)
    b DashZone_ProcessAutoRun_L_800A95A4
    DashZone_ProcessAutoRun_L_800A95A0:
    fadds f3, f3, f0
    DashZone_ProcessAutoRun_L_800A95A4:
    fcmpo cr0, f3, f1
    blt DashZone_ProcessAutoRun_L_800A95A0
    DashZone_ProcessAutoRun_L_800A95AC:
    lfs f1, 0xc(r31)
    lfs f0, lbl_806D4DF4(r2)
    fsubs f1, f1, f3
    fcmpo cr0, f1, f0
    ble DashZone_ProcessAutoRun_L_800A95CC
    lfs f0, lbl_806D4DF0(r2)
    fsubs f1, f1, f0
    b DashZone_ProcessAutoRun_L_800A95E0
    DashZone_ProcessAutoRun_L_800A95CC:
    lfs f0, lbl_806D4DF8(r2)
    fcmpo cr0, f1, f0
    bge DashZone_ProcessAutoRun_L_800A95E0
    lfs f0, lbl_806D4DF0(r2)
    fadds f1, f1, f0
    DashZone_ProcessAutoRun_L_800A95E0:
    lfs f0, lbl_806D4DE8(r2)
    fcmpo cr0, f1, f0
    ble DashZone_ProcessAutoRun_L_800A9614
    fabs f0, f1
    lfs f1, lbl_806D4DFC(r2)
    lfs f2, 0xc(r31)
    frsp f0, f0
    fmuls f0, f1, f0
    fadds f3, f3, f0
    fcmpo cr0, f2, f3
    bge DashZone_ProcessAutoRun_L_800A9638
    fmr f3, f2
    b DashZone_ProcessAutoRun_L_800A9638
    DashZone_ProcessAutoRun_L_800A9614:
    fabs f0, f1
    lfs f1, lbl_806D4DFC(r2)
    lfs f2, 0xc(r31)
    frsp f0, f0
    fmuls f0, f1, f0
    fsubs f3, f3, f0
    fcmpo cr0, f2, f3
    ble DashZone_ProcessAutoRun_L_800A9638
    fmr f3, f2
    DashZone_ProcessAutoRun_L_800A9638:
    stfs f3, 0xc(r31)
    li r3, 0x1
    DashZone_ProcessAutoRun_L_800A9640:
    psq_l f31, 0x18(r1), 0, 0
    lwz r0, 0x24(r1)
    lfd f31, 0x10(r1)
    lwz r31, 0xc(r1)
    mtlr r0
    addi r1, r1, 0x20
    blr
}

asm void WarpAutoRun_GetParam(void) {
    nofralloc
    stwu r1, -0x30(r1)
    mflr r0
    stw r0, 0x34(r1)
    stmw r27, 0x1c(r1)
    mr r28, r4
    mr r27, r3
    mr r29, r5
    mr r30, r6
    mr r31, r7
    lwz r4, 0x4(r3)
    cmpwi r4, -0x1
    bne WarpAutoRun_GetParam_L_800A9694
    li r3, 0x0
    b WarpAutoRun_GetParam_L_800A97E8
    WarpAutoRun_GetParam_L_800A9694:
    lbz r5, 0x20(r27)
    addi r3, r13, -0x7AE8  /* lbl_806CF238 */
    neg r0, r5
    or r0, r0, r5
    rlwinm r0, r0, 3, 29, 29
    lwzx r0, r3, r0
    cmplwi r0, 0x0
    beq WarpAutoRun_GetParam_L_800A9700
    lfd f1, lbl_806D4E00(r2)
    lfs f0, 0x10(r27)
    fmul f1, f1, f0
    frsp f1, f1
    bl fn_8027E9E8
    frsp f2, f1
    lfs f0, 0x14(r27)
    lfd f1, lbl_806D4E00(r2)
    fadds f0, f0, f2
    stfs f0, 0x14(r27)
    lfs f0, 0x10(r27)
    fmul f1, f1, f0
    frsp f1, f1
    bl fn_8027E480
    frsp f1, f1
    lfs f0, 0x1c(r27)
    fadds f0, f0, f1
    stfs f0, 0x1c(r27)
    b WarpAutoRun_GetParam_L_800A9718
    WarpAutoRun_GetParam_L_800A9700:
    lis r3, lbl_80328480@ha
    addi r3, r3, lbl_80328480@l
    crxor 6, 6, 6
    bl DebugPrintf
    li r3, 0x0
    b WarpAutoRun_GetParam_L_800A97E8
    WarpAutoRun_GetParam_L_800A9718:
    lfs f1, 0x14(r27)
    lfs f0, 0x18(r27)
    fmuls f2, f1, f1
    lfs f3, 0x1c(r27)
    fmuls f1, f0, f0
    lfs f0, lbl_806D4DE8(r2)
    fmuls f3, f3, f3
    fadds f1, f2, f1
    fadds f4, f3, f1
    fcmpo cr0, f4, f0
    ble WarpAutoRun_GetParam_L_800A9790
    frsqrte f1, f4
    lfd f3, lbl_806D4E08(r2)
    lfd f2, lbl_806D4E10(r2)
    fmul f0, f1, f1
    fmul f1, f3, f1
    fnmsub f0, f4, f0, f2
    fmul f1, f1, f0
    fmul f0, f1, f1
    fmul f1, f3, f1
    fnmsub f0, f4, f0, f2
    fmul f1, f1, f0
    fmul f0, f1, f1
    fmul f1, f3, f1
    fnmsub f0, f4, f0, f2
    fmul f0, f1, f0
    fmul f0, f4, f0
    frsp f0, f0
    stfs f0, 0x8(r1)
    lfs f4, 0x8(r1)
    WarpAutoRun_GetParam_L_800A9790:
    lfs f0, lbl_806D4E18(r2)
    fcmpo cr0, f4, f0
    ble WarpAutoRun_GetParam_L_800A97C4
    fdivs f1, f0, f4
    lfs f0, 0x14(r27)
    fmuls f0, f0, f1
    stfs f0, 0x14(r27)
    lfs f0, 0x18(r27)
    fmuls f0, f0, f1
    stfs f0, 0x18(r27)
    lfs f0, 0x1c(r27)
    fmuls f0, f0, f1
    stfs f0, 0x1c(r27)
    WarpAutoRun_GetParam_L_800A97C4:
    lfs f0, 0x14(r27)
    li r3, 0x1
    stfs f0, 0x0(r28)
    lfs f0, 0x18(r27)
    stfs f0, 0x0(r29)
    lfs f0, 0x1c(r27)
    stfs f0, 0x0(r30)
    lfs f0, 0xc(r27)
    stfs f0, 0x0(r31)
    WarpAutoRun_GetParam_L_800A97E8:
    lmw r27, 0x1c(r1)
    lwz r0, 0x34(r1)
    mtlr r0
    addi r1, r1, 0x30
    blr
}

void WarpAutoRun_OnEnter(void *self, float f1, float f2, float f3, float f4, float vx, float vy, float vz) {
    *(float *)((char *)self + 0x8) = lbl_806D4E1C;
    *(float *)((char *)self + 0x14) = vx;
    *(float *)((char *)self + 0x18) = vy;
    *(float *)((char *)self + 0x1c) = vz;
    *(int *)self = 1;
}

asm void WarpZone_CheckEntry(void) {
    nofralloc
    stwu r1, -0x20(r1)
    addi r4, r13, -0x7AE8  /* lbl_806CF238 */
    lbz r5, 0x20(r3)
    neg r0, r5
    or r0, r0, r5
    rlwinm r0, r0, 3, 29, 29
    lwzx r6, r4, r0
    cmplwi r6, 0x0
    bne WarpZone_CheckEntry_L_800A9848
    li r3, 0x0
    b WarpZone_CheckEntry_L_800A9984
    WarpZone_CheckEntry_L_800A9848:
    lbz r0, 0x18(r6)
    cmplwi r0, 0x0
    bne WarpZone_CheckEntry_L_800A985C
    li r5, -0x1
    b WarpZone_CheckEntry_L_800A9970
    WarpZone_CheckEntry_L_800A985C:
    lwz r0, 0x10(r6)
    cmpwi r0, 0x0
    bgt WarpZone_CheckEntry_L_800A9870
    li r5, -0x1
    b WarpZone_CheckEntry_L_800A9970
    WarpZone_CheckEntry_L_800A9870:
    li r5, 0x0
    frsp f5, f3
    frsp f6, f1
    mr r4, r5
    stfs f1, 0x8(r1)
    lfs f4, lbl_806D4DE8(r2)
    stfs f2, 0xc(r1)
    stfs f3, 0x10(r1)
    mtctr r0
    ble WarpZone_CheckEntry_L_800A996C
    WarpZone_CheckEntry_L_800A9898:
    lwz r0, 0x14(r6)
    add r7, r0, r4
    lwz r8, 0x0(r7)
    lfs f0, 0xc(r7)
    lfs f1, 0xc(r8)
    lfs f2, 0x14(r8)
    fsubs f3, f6, f1
    lfs f1, 0x4(r7)
    fsubs f2, f5, f2
    fmuls f0, f3, f0
    fneg f2, f2
    fmadds f0, f2, f1, f0
    fcmpo cr0, f0, f4
    ble WarpZone_CheckEntry_L_800A98D8
    li r0, 0x0
    b WarpZone_CheckEntry_L_800A9950
    WarpZone_CheckEntry_L_800A98D8:
    lfs f0, 0x18(r7)
    lfs f1, 0x10(r7)
    fmuls f0, f3, f0
    fmadds f0, f2, f1, f0
    fcmpo cr0, f0, f4
    ble WarpZone_CheckEntry_L_800A98F8
    li r0, 0x0
    b WarpZone_CheckEntry_L_800A9950
    WarpZone_CheckEntry_L_800A98F8:
    lfs f0, 0x24(r8)
    lfs f1, 0x2c(r8)
    fsubs f3, f6, f0
    lfs f0, 0x24(r7)
    fsubs f2, f5, f1
    lfs f1, 0x1c(r7)
    fmuls f0, f3, f0
    fneg f2, f2
    fmadds f0, f2, f1, f0
    fcmpo cr0, f0, f4
    ble WarpZone_CheckEntry_L_800A992C
    li r0, 0x0
    b WarpZone_CheckEntry_L_800A9950
    WarpZone_CheckEntry_L_800A992C:
    lfs f0, 0x30(r7)
    lfs f1, 0x28(r7)
    fmuls f0, f3, f0
    fmadds f0, f2, f1, f0
    fcmpo cr0, f0, f4
    ble WarpZone_CheckEntry_L_800A994C
    li r0, 0x0
    b WarpZone_CheckEntry_L_800A9950
    WarpZone_CheckEntry_L_800A994C:
    li r0, 0x1
    WarpZone_CheckEntry_L_800A9950:
    clrlwi r0, r0, 24
    cmplwi r0, 0x1
    bne WarpZone_CheckEntry_L_800A9960
    b WarpZone_CheckEntry_L_800A9970
    WarpZone_CheckEntry_L_800A9960:
    addi r5, r5, 0x1
    addi r4, r4, 0x50
    bdnz WarpZone_CheckEntry_L_800A9898
    WarpZone_CheckEntry_L_800A996C:
    li r5, -0x1
    WarpZone_CheckEntry_L_800A9970:
    subfic r4, r5, -0x1
    addi r0, r5, 0x1
    or r0, r4, r0
    stw r5, 0x4(r3)
    srwi r3, r0, 31
    WarpZone_CheckEntry_L_800A9984:
    addi r1, r1, 0x20
    blr
}

asm void Field4NotMinusOne(void) {
    nofralloc
    lwz r4, 0x4(r3)
    subfic r3, r4, -0x1
    addi r0, r4, 0x1
    or r0, r3, r0
    srwi r3, r0, 31
    blr
}

asm void WarpZone_CalcEdgeVectors(void) {
    nofralloc
    stwu r1, -0x20(r1)
    mflr r0
    lis r5, dtor_80036E40@ha
    li r6, 0xc
    stw r0, 0x24(r1)
    addi r5, r5, dtor_80036E40@l
    li r7, 0x4
    stw r31, 0x1c(r1)
    mr r31, r3
    lis r3, fn_8007C5DC@ha
    stw r4, 0x0(r31)
    addi r4, r3, fn_8007C5DC@l
    addi r3, r31, 0x4
    bl fn_80270D6C
    li r0, 0x2
    li r12, 0x0
    li r9, 0x0
    mtctr r0
    WarpZone_CalcEdgeVectors_L_800A99EC:
    addi r5, r12, 0x1
    lwz r10, 0x0(r31)
    slwi r3, r5, 30
    addi r6, r9, 0x4
    srwi r8, r5, 31
    addi r5, r12, 0x2
    subf r3, r8, r3
    lfsx f0, r10, r9
    rotlwi r7, r3, 2
    addi r4, r9, 0x8
    add r7, r7, r8
    slwi r3, r5, 30
    mulli r11, r7, 0xc
    srwi r8, r5, 31
    addi r0, r9, 0xc
    subf r3, r8, r3
    lfsx f1, r10, r11
    rotlwi r7, r3, 2
    add r7, r7, r8
    addi r5, r11, 0x4
    fsubs f0, f1, f0
    addi r3, r11, 0x8
    mulli r11, r7, 0xc
    addi r12, r12, 0x2
    stfsx f0, r31, r6
    lwz r7, 0x0(r31)
    lfsx f1, r7, r5
    addi r5, r11, 0x4
    lfsx f0, r7, r6
    addi r6, r9, 0x10
    fsubs f0, f1, f0
    stfsx f0, r31, r4
    lwz r7, 0x0(r31)
    lfsx f1, r7, r3
    addi r3, r11, 0x8
    lfsx f0, r7, r4
    addi r4, r9, 0x14
    fsubs f0, f1, f0
    stfsx f0, r31, r0
    addi r0, r9, 0x18
    addi r9, r9, 0xc
    lwz r10, 0x0(r31)
    lfsx f0, r10, r9
    addi r9, r9, 0xc
    lfsx f1, r10, r11
    fsubs f0, f1, f0
    stfsx f0, r31, r6
    lwz r7, 0x0(r31)
    lfsx f1, r7, r5
    lfsx f0, r7, r6
    fsubs f0, f1, f0
    stfsx f0, r31, r4
    lwz r7, 0x0(r31)
    lfsx f1, r7, r3
    lfsx f0, r7, r4
    fsubs f0, f1, f0
    stfsx f0, r31, r0
    bdnz WarpZone_CalcEdgeVectors_L_800A99EC
    lfs f3, 0xc(r31)
    lfs f2, 0x8(r31)
    lfs f1, 0x4(r31)
    lfs f0, lbl_806D4DE8(r2)
    stfs f1, 0x34(r31)
    stfs f2, 0x38(r31)
    stfs f3, 0x3c(r31)
    lfs f2, 0x34(r31)
    lfs f1, 0x38(r31)
    lfs f3, 0x3c(r31)
    fmuls f2, f2, f2
    fmuls f1, f1, f1
    fmuls f3, f3, f3
    fadds f1, f2, f1
    fadds f4, f3, f1
    fcmpo cr0, f4, f0
    ble WarpZone_CalcEdgeVectors_L_800A9B64
    frsqrte f1, f4
    lfd f3, lbl_806D4E08(r2)
    lfd f2, lbl_806D4E10(r2)
    fmul f0, f1, f1
    fmul f1, f3, f1
    fnmsub f0, f4, f0, f2
    fmul f1, f1, f0
    fmul f0, f1, f1
    fmul f1, f3, f1
    fnmsub f0, f4, f0, f2
    fmul f1, f1, f0
    fmul f0, f1, f1
    fmul f1, f3, f1
    fnmsub f0, f4, f0, f2
    fmul f0, f1, f0
    fmul f0, f4, f0
    frsp f0, f0
    stfs f0, 0xc(r1)
    lfs f4, 0xc(r1)
    WarpZone_CalcEdgeVectors_L_800A9B64:
    lfs f0, lbl_806D4DE8(r2)
    fcmpo cr0, f4, f0
    cror eq, lt, eq
    bne WarpZone_CalcEdgeVectors_L_800A9B84
    stfs f0, 0x3c(r31)
    stfs f0, 0x38(r31)
    stfs f0, 0x34(r31)
    b WarpZone_CalcEdgeVectors_L_800A9BB0
    WarpZone_CalcEdgeVectors_L_800A9B84:
    lfs f1, lbl_806D4E20(r2)
    lfs f0, 0x34(r31)
    fdivs f1, f1, f4
    fmuls f0, f0, f1
    stfs f0, 0x34(r31)
    lfs f0, 0x38(r31)
    fmuls f0, f0, f1
    stfs f0, 0x38(r31)
    lfs f0, 0x3c(r31)
    fmuls f0, f0, f1
    stfs f0, 0x3c(r31)
    WarpZone_CalcEdgeVectors_L_800A9BB0:
    lwz r3, 0x0(r31)
    lfs f0, lbl_806D4DE8(r2)
    lfs f2, 0x3c(r3)
    lfs f1, 0x30(r3)
    fsubs f1, f2, f1
    stfs f1, 0x40(r31)
    lwz r3, 0x0(r31)
    lfs f2, 0x40(r3)
    lfs f1, 0x34(r3)
    fsubs f1, f2, f1
    stfs f1, 0x44(r31)
    lwz r3, 0x0(r31)
    lfs f2, 0x44(r3)
    lfs f1, 0x38(r3)
    fsubs f1, f2, f1
    stfs f1, 0x48(r31)
    lfs f2, 0x40(r31)
    lfs f1, 0x44(r31)
    lfs f3, 0x48(r31)
    fmuls f2, f2, f2
    fmuls f1, f1, f1
    fmuls f3, f3, f3
    fadds f1, f2, f1
    fadds f4, f3, f1
    fcmpo cr0, f4, f0
    ble WarpZone_CalcEdgeVectors_L_800A9C64
    frsqrte f1, f4
    lfd f3, lbl_806D4E08(r2)
    lfd f2, lbl_806D4E10(r2)
    fmul f0, f1, f1
    fmul f1, f3, f1
    fnmsub f0, f4, f0, f2
    fmul f1, f1, f0
    fmul f0, f1, f1
    fmul f1, f3, f1
    fnmsub f0, f4, f0, f2
    fmul f1, f1, f0
    fmul f0, f1, f1
    fmul f1, f3, f1
    fnmsub f0, f4, f0, f2
    fmul f0, f1, f0
    fmul f0, f4, f0
    frsp f0, f0
    stfs f0, 0x8(r1)
    lfs f4, 0x8(r1)
    WarpZone_CalcEdgeVectors_L_800A9C64:
    lfs f0, lbl_806D4DE8(r2)
    fcmpo cr0, f4, f0
    cror eq, lt, eq
    bne WarpZone_CalcEdgeVectors_L_800A9C84
    stfs f0, 0x48(r31)
    stfs f0, 0x44(r31)
    stfs f0, 0x40(r31)
    b WarpZone_CalcEdgeVectors_L_800A9CB0
    WarpZone_CalcEdgeVectors_L_800A9C84:
    lfs f1, lbl_806D4E20(r2)
    lfs f0, 0x40(r31)
    fdivs f1, f1, f4
    fmuls f0, f0, f1
    stfs f0, 0x40(r31)
    lfs f0, 0x44(r31)
    fmuls f0, f0, f1
    stfs f0, 0x44(r31)
    lfs f0, 0x48(r31)
    fmuls f0, f0, f1
    stfs f0, 0x48(r31)
    WarpZone_CalcEdgeVectors_L_800A9CB0:
    lwz r0, 0x24(r1)
    mr r3, r31
    lwz r31, 0x1c(r1)
    mtlr r0
    addi r1, r1, 0x20
    blr
}

void *dtor_800A9CC8(void *this, short flag) {
    if (this != 0) {
        fn_80270CF4((char *)this + 4, &dtor_80036E40, 0xc, 0x4);
        if (flag > 0) {
            MemoryManager_TimedFree(this);
        }
    }
    return this;
}

#pragma exceptions off
void *dtor_800A9D2C(void *this, short flag) {
    if (this) {
        if (this) {
            dtor_800AA69C(this, 0);
        }
        if (flag > 0) {
            MemoryManager_TimedFree(this);
        }
    }
    return this;
}
#pragma exceptions reset

