/*
 * dtk reversed-extab group `auto_03_801223E8_text` bundle (1 TU, indivisible).
 * 11 functions, no extab/extabindex entries (group is text-only — dtk groups
 * fns by `auto_*_text*.s` file boundary, not by extab presence).
 *
 * Phase 3a-small probe: all 11 fns held as asm_fn. Promote 1 fn at a time
 * via sub-agent dispatch (asm_fn -> matched). Mixed contents (ResourceTable_*
 * getters + NokoNokoChallenge_HandleBrakeInput + fn_801228D4): TU named with
 * neutral group-id; rename retroactively once decomp identifies the module.
 *
 * Generated by `python tools/extract_fn_asm.py auto_03_801223E8_text`.
 * Re-run to regenerate; hand edits below this header may be overwritten.
 *
 * See docs/per_fn_matching_strategy.md §13 and
 * docs/large_extab_group_strategy.md (Phase 3a).
 */

/* === extracted from auto_03_801223E8_text === */
/* Copy into the TU between forward decls and function bodies; */
/* keep emit order = target section layout (do not sort). */

/* --- extern decls: sda21-referenced data --- */
extern unsigned int gResTableCacheIdx;
extern unsigned int gResTableCacheKey;
extern unsigned int g_ccClass;
extern unsigned int lbl_806D6DE0;
extern unsigned int lbl_806D6E0C;
extern unsigned int lbl_806D6E10;
extern unsigned int lbl_806D6E40;
extern unsigned int lbl_806D6E44;
extern unsigned int lbl_806D6E48;

/* --- extern decls: large-data refs (@ha/@l pairs) --- */
extern unsigned int kResourcePathTable[];
extern unsigned int kResourceTableExt[];
extern unsigned int kResourceTableMain[];
extern unsigned int lbl_80355018[];
extern unsigned int lbl_80355068;

/* --- forward decls --- */
unsigned char ResourceTable_GetFlagsByte(int id);
void ResourceTable_GetScaleXY(int id, float *outX, float *outY);
short ResourceTable_GetChainNextId(int id);
void ResourceTable_GetSizeXY(int id, float *out_x, float *out_y);
void ResourceTable_GetOffsetXY(int id, float *outX, float *outY);
short ResourceTable_GetSlotIndex(int id);
asm void fn_801228D4(void);
const char *ResourceTable_GetFilePathPtr(int id);
short ResourceTable_GetGroupKey(int id);
int IsValidResourceId(int id);
asm void NokoNokoChallenge_HandleBrakeInput(void);

/* --- asm function bodies (.text order = fn address order) --- */
typedef struct ResourceTableEntry {
    short id;            /* 0x00 */
    char _pad02[0x2];    /* 0x02..0x03 */
    float offset_x;      /* 0x04 */
    float offset_y;      /* 0x08 */
    char _pad0C[0x10];   /* 0x0C..0x1b */
    float scaleX;        /* 0x1c */
    float scaleY;        /* 0x20 */
    unsigned char flags; /* 0x24 */
    char _pad25[0x3];    /* 0x25..0x27 (stride 0x28) */
} ResourceTableEntry;

unsigned char ResourceTable_GetFlagsByte(int id) {
    ResourceTableEntry *entry;
    ResourceTableEntry *p;
    int i;

    if (id == (int)gResTableCacheKey) {
        if (id < 0x2b00) {
            entry = &((ResourceTableEntry *)kResourceTableMain)[gResTableCacheIdx];
        } else {
            entry = &((ResourceTableEntry *)kResourceTableExt)[gResTableCacheIdx];
        }
    } else if (id < 0x2b00) {
        gResTableCacheIdx = id;
        gResTableCacheKey = id;
        entry = &((ResourceTableEntry *)kResourceTableMain)[id];
    } else {
        p = (ResourceTableEntry *)kResourceTableExt;
        for (i = 0; i < 4; i++) {
            if (id == p->id) {
                gResTableCacheKey = id;
                gResTableCacheIdx = i;
                entry = &((ResourceTableEntry *)kResourceTableExt)[i];
                goto check_entry;
            }
            p++;
        }
        entry = 0;
    }

check_entry:
    if (entry != 0) {
        return entry->flags;
    }
    return 4;
}

void ResourceTable_GetScaleXY(int id, float *outX, float *outY) {
    ResourceTableEntry *entry;
    ResourceTableEntry *p;
    float sx = *(float *)&lbl_806D6E0C;
    float sy = sx;
    int i;

    if (id == (int)gResTableCacheKey) {
        if (id < 0x2b00) {
            entry = &((ResourceTableEntry *)kResourceTableMain)[gResTableCacheIdx];
        } else {
            entry = &((ResourceTableEntry *)kResourceTableExt)[gResTableCacheIdx];
        }
    } else if (id < 0x2b00) {
        gResTableCacheIdx = id;
        gResTableCacheKey = id;
        entry = &((ResourceTableEntry *)kResourceTableMain)[id];
    } else {
        p = (ResourceTableEntry *)kResourceTableExt;
        for (i = 0; i < 4; i++) {
            if (id == p->id) {
                gResTableCacheKey = id;
                gResTableCacheIdx = i;
                entry = &((ResourceTableEntry *)kResourceTableExt)[i];
                goto check_entry;
            }
            p++;
        }
        entry = 0;
    }

check_entry:
    if (entry != 0) {
        sx = entry->scaleX;
        sy = entry->scaleY;
    }
    *outX = sx;
    *outY = sy;
}

short ResourceTable_GetChainNextId(int id) {
    ResourceTableEntry *entry;
    ResourceTableEntry *p;
    int i;

    if (id == (int)gResTableCacheKey) {
        if (id < 0x2b00) {
            entry = &((ResourceTableEntry *)kResourceTableMain)[gResTableCacheIdx];
        } else {
            entry = &((ResourceTableEntry *)kResourceTableExt)[gResTableCacheIdx];
        }
    } else if (id < 0x2b00) {
        gResTableCacheIdx = id;
        gResTableCacheKey = id;
        entry = &((ResourceTableEntry *)kResourceTableMain)[id];
    } else {
        p = (ResourceTableEntry *)kResourceTableExt;
        for (i = 0; i < 4; i++) {
            if (id == p->id) {
                gResTableCacheKey = id;
                gResTableCacheIdx = i;
                entry = &((ResourceTableEntry *)kResourceTableExt)[i];
                goto check_entry;
            }
            p++;
        }
        entry = 0;
    }

check_entry:
    if (entry != 0) {
        return *(short *)((char *)entry + 0x18);
    }
    return -1;
}

void ResourceTable_GetSizeXY(int id, float *out_x, float *out_y) {
    ResourceTableEntry *entry;
    ResourceTableEntry *p;
    int i;
    float x;
    float y;

    x = *(float *)&lbl_806D6E0C;
    y = x;

    if (id == (int)gResTableCacheKey) {
        if (id < 0x2b00) {
            entry = &((ResourceTableEntry *)kResourceTableMain)[gResTableCacheIdx];
        } else {
            entry = &((ResourceTableEntry *)kResourceTableExt)[gResTableCacheIdx];
        }
    } else if (id < 0x2b00) {
        gResTableCacheIdx = id;
        gResTableCacheKey = id;
        entry = &((ResourceTableEntry *)kResourceTableMain)[id];
    } else {
        p = (ResourceTableEntry *)kResourceTableExt;
        for (i = 0; i < 4; i++) {
            if (id == p->id) {
                gResTableCacheKey = id;
                gResTableCacheIdx = i;
                entry = &((ResourceTableEntry *)kResourceTableExt)[i];
                goto check_entry;
            }
            p++;
        }
        entry = 0;
    }

check_entry:
    if (entry != 0) {
        x = *(float *)((char *)entry + 0xc);
        y = *(float *)((char *)entry + 0x10);
    }
    *out_x = x;
    *out_y = y;
}

void ResourceTable_GetOffsetXY(int id, float *outX, float *outY) {
    ResourceTableEntry *entry;
    ResourceTableEntry *p;
    int i;
    float x = *(float *)&lbl_806D6E10;
    float y = x;

    if (id == (int)gResTableCacheKey) {
        if (id < 0x2b00) {
            entry = &((ResourceTableEntry *)kResourceTableMain)[gResTableCacheIdx];
        } else {
            entry = &((ResourceTableEntry *)kResourceTableExt)[gResTableCacheIdx];
        }
    } else if (id < 0x2b00) {
        gResTableCacheIdx = id;
        gResTableCacheKey = id;
        entry = &((ResourceTableEntry *)kResourceTableMain)[id];
    } else {
        p = (ResourceTableEntry *)kResourceTableExt;
        for (i = 0; i < 4; i++) {
            if (id == p->id) {
                gResTableCacheKey = id;
                gResTableCacheIdx = i;
                entry = &((ResourceTableEntry *)kResourceTableExt)[i];
                goto check_entry;
            }
            p++;
        }
        entry = 0;
    }

check_entry:
    if (entry != 0) {
        x = entry->offset_x;
        y = entry->offset_y;
    }
    *outX = x;
    *outY = y;
}

short ResourceTable_GetSlotIndex(int id) {
    ResourceTableEntry *entry;
    ResourceTableEntry *p;
    int i;

    if (id == (int)gResTableCacheKey) {
        if (id < 0x2b00) {
            entry = &((ResourceTableEntry *)kResourceTableMain)[gResTableCacheIdx];
        } else {
            entry = &((ResourceTableEntry *)kResourceTableExt)[gResTableCacheIdx];
        }
    } else if (id < 0x2b00) {
        gResTableCacheIdx = id;
        gResTableCacheKey = id;
        entry = &((ResourceTableEntry *)kResourceTableMain)[id];
    } else {
        p = (ResourceTableEntry *)kResourceTableExt;
        for (i = 0; i < 4; i++) {
            if (id == p->id) {
                gResTableCacheKey = id;
                gResTableCacheIdx = i;
                entry = &((ResourceTableEntry *)kResourceTableExt)[i];
                goto check_entry;
            }
            p++;
        }
        entry = 0;
    }

check_entry:
    if (entry != 0) {
        return *(short *)((char *)entry + 0x14);
    }
    return -1;
}

asm void fn_801228D4(void) {
    nofralloc
    cmpwi r3, 0x2b00
    bge fn_801228D4_L_801229A8
    lwz r0, gResTableCacheKey(r13)
    cmpw r3, r0
    bne fn_801228D4_L_80122920
    cmpwi r3, 0x2b00
    bge fn_801228D4_L_80122908
    lwz r4, gResTableCacheIdx(r13)
    lis r3, kResourceTableMain@ha
    addi r0, r3, kResourceTableMain@l
    mulli r3, r4, 0x28
    add r0, r0, r3
    b fn_801228D4_L_80122990
    fn_801228D4_L_80122908:
    lwz r4, gResTableCacheIdx(r13)
    lis r3, kResourceTableExt@ha
    addi r0, r3, kResourceTableExt@l
    mulli r3, r4, 0x28
    add r0, r0, r3
    b fn_801228D4_L_80122990
    fn_801228D4_L_80122920:
    cmpwi r3, 0x2b00
    bge fn_801228D4_L_80122944
    mulli r5, r3, 0x28
    lis r4, kResourceTableMain@ha
    stw r3, gResTableCacheIdx(r13)
    addi r0, r4, kResourceTableMain@l
    stw r3, gResTableCacheKey(r13)
    add r0, r0, r5
    b fn_801228D4_L_80122990
    fn_801228D4_L_80122944:
    lis r4, kResourceTableExt@ha
    li r0, 0x4
    addi r4, r4, kResourceTableExt@l
    li r6, 0x0
    mtctr r0
    fn_801228D4_L_80122958:
    lha r0, 0x0(r4)
    cmpw r3, r0
    bne fn_801228D4_L_80122980
    mulli r5, r6, 0x28
    lis r4, kResourceTableExt@ha
    stw r3, gResTableCacheKey(r13)
    addi r0, r4, kResourceTableExt@l
    stw r6, gResTableCacheIdx(r13)
    add r0, r0, r5
    b fn_801228D4_L_80122990
    fn_801228D4_L_80122980:
    addi r4, r4, 0x28
    addi r6, r6, 0x1
    bdnz fn_801228D4_L_80122958
    li r0, 0x0
    fn_801228D4_L_80122990:
    cmplwi r0, 0x0
    beq fn_801228D4_L_801229A0
    lwz r3, lbl_806D6DE0(r2)
    blr
    fn_801228D4_L_801229A0:
    li r3, 0x0
    blr
    fn_801228D4_L_801229A8:
    lis r4, lbl_80355068@ha
    slwi r0, r3, 2
    addi r3, r4, lbl_80355068@l
    subis r3, r3, 0x1
    add r3, r3, r0
    lwz r3, 0x5400(r3)
    blr
}

const char *ResourceTable_GetFilePathPtr(int id) {
    ResourceTableEntry *entry;
    ResourceTableEntry *p;
    int i;
    short path_idx;

    if (id < 0x2b00) {
        if (id == (int)gResTableCacheKey) {
            if (id < 0x2b00) {
                entry = &((ResourceTableEntry *)kResourceTableMain)[gResTableCacheIdx];
            } else {
                entry = &((ResourceTableEntry *)kResourceTableExt)[gResTableCacheIdx];
            }
        } else if (id < 0x2b00) {
            gResTableCacheIdx = id;
            gResTableCacheKey = id;
            entry = &((ResourceTableEntry *)kResourceTableMain)[id];
        } else {
            p = (ResourceTableEntry *)kResourceTableExt;
            for (i = 0; i < 4; i++) {
                if (id == p->id) {
                    gResTableCacheKey = id;
                    gResTableCacheIdx = i;
                    entry = &((ResourceTableEntry *)kResourceTableExt)[i];
                    goto check_entry;
                }
                p++;
            }
            entry = 0;
        }

    check_entry:
        if (entry != 0) {
            path_idx = *(short *)((char *)entry + 0x16);
            return (const char *)kResourcePathTable[path_idx];
        }
        return 0;
    }
    return (const char *)lbl_80355018[id - 0x2b00];
}

short ResourceTable_GetGroupKey(int id) {
    ResourceTableEntry *entry;
    ResourceTableEntry *p;
    int i;

    if (id == (int)gResTableCacheKey) {
        if (id < 0x2b00) {
            entry = &((ResourceTableEntry *)kResourceTableMain)[gResTableCacheIdx];
        } else {
            entry = &((ResourceTableEntry *)kResourceTableExt)[gResTableCacheIdx];
        }
    } else if (id < 0x2b00) {
        gResTableCacheIdx = id;
        gResTableCacheKey = id;
        entry = &((ResourceTableEntry *)kResourceTableMain)[id];
    } else {
        p = (ResourceTableEntry *)kResourceTableExt;
        for (i = 0; i < 4; i++) {
            if (id == p->id) {
                gResTableCacheKey = id;
                gResTableCacheIdx = i;
                entry = &((ResourceTableEntry *)kResourceTableExt)[i];
                goto check_entry;
            }
            p++;
        }
        entry = 0;
    }

check_entry:
    if (entry != 0) {
        return *(short *)((char *)entry + 0x16);
    }
    return 0;
}

int IsValidResourceId(int id) {
    if (id > -1 && id < 0x2b04) {
        return 1;
    }
    return 0;
}

asm void NokoNokoChallenge_HandleBrakeInput(void) {
    nofralloc
    clrlwi. r0, r4, 24
    beq NokoNokoChallenge_HandleBrakeInput_L_80122BC4
    lwz r0, g_ccClass(r13)
    cmpwi r0, 0x2
    bne NokoNokoChallenge_HandleBrakeInput_L_80122BD4
    NokoNokoChallenge_HandleBrakeInput_L_80122BC4:
    lfs f0, lbl_806D6E40(r2)
    stfs f0, 0x4(r3)
    li r3, 0x0
    blr
    NokoNokoChallenge_HandleBrakeInput_L_80122BD4:
    lfs f2, 0x4(r3)
    lfs f1, lbl_806D6E44(r2)
    lfs f0, lbl_806D6E48(r2)
    fadds f1, f2, f1
    stfs f1, 0x4(r3)
    lfs f1, 0x4(r3)
    fcmpo cr0, f1, f0
    cror eq, gt, eq
    bne NokoNokoChallenge_HandleBrakeInput_L_80122C04
    stfs f0, 0x4(r3)
    li r3, 0x1
    blr
    NokoNokoChallenge_HandleBrakeInput_L_80122C04:
    li r3, 0x0
    blr
}

