/*
 * dtk reversed-extab group `auto_fn_800ABD80_text` bundle (1 TU, indivisible).
 * 6 functions sharing one extab group: fn_800ABD80 (asm_fn), the 4
 * CourseData lookup fns (primary matching targets of
 * batch_text_800abdfc_coursedata_bundle), and dtor_800ABF10 (asm_fn).
 *
 * fn_800ABD80 / dtor_800ABF10 are out of batch scope and kept as asm_fn
 * so the indivisible group's extab/extabindex layout stays
 * byte-identical to the target.
 *
 * Initial scaffold generated by `python tools/extract_fn_asm.py
 * auto_fn_800ABD80_text`.
 *
 * See docs/per_fn_matching_strategy.md §12-14 and
 * docs/large_extab_group_strategy.md.
 */

/* --- extern decls: branch callees (bl/b targets) --- */
extern void Alloc();
extern void CourseData_LoadPathTable();
extern void DebugPrintf();
extern void MemoryManager_Free();
extern void dtor_8003AFB8();

/* --- extern decls: sda21-referenced data --- */
extern void *g_courseData;

/* --- extern decls: large-data refs (@ha/@l pairs) --- */
extern unsigned int lbl_80328B7C[];
extern unsigned int lbl_80419DB0[];
extern unsigned int lbl_80419DBC[];

/* --- forward decls --- */
asm void fn_800ABD80(void);
int CourseData_ResolveByKey(void *p, unsigned int key);
void *CourseData_GetDefaultPathKey(void *p);
void *CourseData_GetPath(void *p, int idx);
asm void CourseData_GetOrCreate(void);
asm void dtor_800ABF10(void);

/* --- extab (manual emit, .extab_user -> extab via objcopy) ---
 *
 * All three extab-bearing fns in this group are asm_fn (fn_800ABD80,
 * CourseData_GetOrCreate, dtor_800ABF10), so all extab/extabindex
 * entries are manually emitted. CourseData_GetOrCreate's extab encodes
 * a DELETEPOINTER cleanup on r28 at PC 0x70 (calls dtor_8003AFB8 if an
 * exception propagates) -- that C++ unwind shape didn't reproduce from
 * plain C with #pragma exceptions on (auto-emitted plain prologue
 * extab, missing the DELETEPOINTER action).
 */
#pragma section R ".extab_user"
__declspec(section ".extab_user") static const unsigned char extab_dtor_800ABF10[8] = {
    0x08, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_fn_800ABD80[8] = {
    0x10, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const struct { unsigned int f0; unsigned int f1; unsigned int f2; unsigned int f3; unsigned int f4; void *f5; } extab_CourseData_GetOrCreate = { 0x20080000, 0x00000070, 0x00000010, 0x00000000, 0x8A80001C, (void *)&dtor_8003AFB8 };

/* --- extabindex (manual emit, .extabindex_user -> extabindex via objcopy) --- */
#pragma section R ".extabindex_user"
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_fn_800ABD80 = {
    (void *)&fn_800ABD80, 0x0000007C, (void *)extab_fn_800ABD80
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_CourseData_GetOrCreate = {
    (void *)&CourseData_GetOrCreate, 0x000000A0, (void *)&extab_CourseData_GetOrCreate
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_dtor_800ABF10 = {
    (void *)&dtor_800ABF10, 0x00000048, (void *)extab_dtor_800ABF10
};

/* --- asm function bodies (.text order = fn address order) --- */
asm void fn_800ABD80(void) {
    nofralloc
    stwu r1, -0x10(r1)
    mflr r0
    stw r0, 0x14(r1)
    stw r31, 0xc(r1)
    mr r31, r4
    stw r30, 0x8(r1)
    mr. r30, r3
    beq fn_800ABD80_L_800ABDE0
    lis r3, lbl_80419DB0@ha
    addi r0, r3, lbl_80419DB0@l
    stw r0, 0x0(r30)
    lwz r3, 0x8(r30)
    bl MemoryManager_Free
    lwz r3, 0x4(r30)
    bl MemoryManager_Free
    cmplwi r30, 0x0
    beq fn_800ABD80_L_800ABDD0
    lis r3, lbl_80419DBC@ha
    addi r0, r3, lbl_80419DBC@l
    stw r0, 0x0(r30)
    fn_800ABD80_L_800ABDD0:
    extsh. r0, r31
    ble fn_800ABD80_L_800ABDE0
    mr r3, r30
    bl dtor_8003AFB8
    fn_800ABD80_L_800ABDE0:
    lwz r0, 0x14(r1)
    mr r3, r30
    lwz r31, 0xc(r1)
    lwz r30, 0x8(r1)
    mtlr r0
    addi r1, r1, 0x10
    blr
}

/*
 * Linear search a NULL-terminated key array (p->keys[]) for `key`, return
 * the corresponding value from a parallel value array (p->vals[]). -1 on
 * miss.
 */
int CourseData_ResolveByKey(void *p, unsigned int key) {
    unsigned int *keys = ((unsigned int **)p)[1];
    int i = 0;
    while (*keys != 0) {
        if (*keys == key) {
            return ((int **)p)[2][i];
        }
        keys++;
        i++;
    }
    return -1;
}

/*
 * Trivial accessor: return p->paths->default_key (offset 0x18 of the path
 * table pointed to by p->paths).
 */
void *CourseData_GetDefaultPathKey(void *p) {
    return *(void **)((char *)*(void **)((char *)p + 4) + 0x18);
}

/*
 * Bounded path-by-index lookup: return p->paths[idx] for 0 <= idx < 6,
 * else NULL.
 */
void *CourseData_GetPath(void *p, int idx) {
    if (idx < 0) goto bad;
    if (idx < 6) goto good;
bad:
    return 0;
good:
    return ((void **)*(void **)((char *)p + 4))[idx];
}

/*
 * Lazy CourseData factory (asm_fn): logs a "create line manager" string,
 * allocates a 12-byte instance if g_courseData is NULL, populates via
 * CourseData_LoadPathTable, returns current g_courseData.
 *
 * Held as asm_fn because the target extab encodes a DELETEPOINTER
 * cleanup action on r28 at PC 0x70 (dtor_8003AFB8 -- a C++ unwind shape
 * that didn't reproduce from plain C with #pragma exceptions on).
 */
asm void CourseData_GetOrCreate(void) {
    nofralloc
    stwu r1, -0x20(r1)
    mflr r0
    lis r6, lbl_80328B7C@ha
    stw r0, 0x24(r1)
    stw r31, 0x1c(r1)
    mr r31, r5
    stw r30, 0x18(r1)
    mr r30, r4
    stw r29, 0x14(r1)
    mr r29, r3
    addi r3, r6, lbl_80328B7C@l
    stw r28, 0x10(r1)
    crxor 6, 6, 6
    bl DebugPrintf
    lwz r0, g_courseData(r13)
    cmplwi r0, 0x0
    bne CourseData_GetOrCreate_L_800ABEB8
    li r0, 0x0
    CourseData_GetOrCreate_L_800ABEB8:
    cmplwi r0, 0x0
    bne CourseData_GetOrCreate_L_800ABEE0
    li r3, 0xc
    bl Alloc
    mr. r28, r3
    beq CourseData_GetOrCreate_L_800ABEE0
    mr r4, r29
    mr r5, r30
    mr r6, r31
    bl CourseData_LoadPathTable
    CourseData_GetOrCreate_L_800ABEE0:
    lwz r3, g_courseData(r13)
    cmplwi r3, 0x0
    bne CourseData_GetOrCreate_L_800ABEF0
    li r3, 0x0
    CourseData_GetOrCreate_L_800ABEF0:
    lwz r0, 0x24(r1)
    lwz r31, 0x1c(r1)
    lwz r30, 0x18(r1)
    lwz r29, 0x14(r1)
    lwz r28, 0x10(r1)
    mtlr r0
    addi r1, r1, 0x20
    blr
}

asm void dtor_800ABF10(void) {
    nofralloc
    stwu r1, -0x10(r1)
    mflr r0
    stw r0, 0x14(r1)
    stw r31, 0xc(r1)
    mr. r31, r3
    beq dtor_800ABF10_L_800ABF40
    lis r5, lbl_80419DBC@ha
    extsh. r0, r4
    addi r0, r5, lbl_80419DBC@l
    stw r0, 0x0(r31)
    ble dtor_800ABF10_L_800ABF40
    bl dtor_8003AFB8
    dtor_800ABF10_L_800ABF40:
    lwz r0, 0x14(r1)
    mr r3, r31
    lwz r31, 0xc(r1)
    mtlr r0
    addi r1, r1, 0x10
    blr
}
