/*
 * dtor group @ 0x801FEA70..0x801FEBD8 (3 functions, total size 0x168).
 *
 * Reversed extab group `auto_dtor_801FEA70_text` is indivisible (dtk
 * fails with `Conflicting splits within reversed extab group` if any of
 * the 3 dtors is split out), so all three live in this single TU.
 *
 *   dtor_801FEA70 (size 0x48): vtable-setter dtor for class A whose
 *     vtable lives at lbl_804EC1C8 (.data, size 0x14). Writes the
 *     vtable into *this then calls dtor_8003AFB8 (MemoryManager_TimedFree)
 *     when the deleting-flag is positive.
 *
 *   dtor_801FEAB8 / dtor_801FEB48 (size 0x90 each, byte-identical):
 *     owns-pointer dtors. Read member ptr at offset 0, dispatch its
 *     vtable[+0x8] entry with arg=1 (deleting flag), then TimedFree
 *     under the same flag > 0 gate. Both functions have C++ exception
 *     specification scaffolding (Frame Pointer + SPECIFICATION +
 *     ACTIVECATCHBLOCK extab) with an `fn_8027248C` (__terminate /
 *     unexpected) cleanup handler for the virtual call site.
 *
 * Implemented as asm_fn for all three: dtor_801FEA70 alone could be C
 * (vtable-write + simple TimedFree pattern, cf. GameModeBase_Dtor) but
 * the manual extab/extabindex layout below would need to be reordered
 * if any single function were promoted, so the whole bundle stays asm.
 * Future promote pass should follow docs/per_fn_matching_strategy.md
 * §14.1 (Approach A: drop manual emit, let CW auto-emit + section
 * placement coalesce).
 *
 * Generated by tools/extract_fn_asm.py auto_dtor_801FEA70_text.
 */

/* --- extern decls: branch callees (bl/b targets) --- */
/* Open prototype (`extern void Foo();`) accepts any call signature; */
/* refine if the real prototype matters for header consumers. */
extern void dtor_8003AFB8();
extern void fn_8027248C();

/* --- extern decls: large-data refs (@ha/@l pairs) --- */
/* Open array (`[]`) avoids sda21 strict-mode link errors when a future */
/* promote rewrites the asm_fn to C and references the symbol as `arr[i]`. */
extern unsigned int lbl_804EC1C8[];

/* --- forward decls --- */
asm void dtor_801FEA70(void);
asm void dtor_801FEAB8(void);
asm void dtor_801FEB48(void);

/* --- extab (manual emit, .extab_user -> extab via objcopy) --- */
#pragma section R ".extab_user"
__declspec(section ".extab_user") static const unsigned char extab_dtor_801FEAB8[40] = {
    0x18, 0x18, 0x00, 0x00, 0x00, 0x00, 0x00, 0x48,
    0x00, 0x04, 0x00, 0x18, 0x00, 0x00, 0x00, 0x68,
    0x00, 0x00, 0x00, 0x24, 0x00, 0x00, 0x00, 0x00,
    0x8F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x60,
    0x00, 0x00, 0x00, 0x08, 0x8D, 0x00, 0x00, 0x08
};
__declspec(section ".extab_user") static const unsigned char extab_dtor_801FEB48[40] = {
    0x18, 0x18, 0x00, 0x00, 0x00, 0x00, 0x00, 0x48,
    0x00, 0x04, 0x00, 0x18, 0x00, 0x00, 0x00, 0x68,
    0x00, 0x00, 0x00, 0x24, 0x00, 0x00, 0x00, 0x00,
    0x8F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x60,
    0x00, 0x00, 0x00, 0x08, 0x8D, 0x00, 0x00, 0x08
};
__declspec(section ".extab_user") static const unsigned char extab_dtor_801FEA70[8] = {
    0x08, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

/* --- extabindex (manual emit, .extabindex_user -> extabindex via objcopy) --- */
#pragma section R ".extabindex_user"
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_dtor_801FEA70 = {
    (void *)&dtor_801FEA70, 0x00000048, (void *)extab_dtor_801FEA70
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_dtor_801FEAB8 = {
    (void *)&dtor_801FEAB8, 0x00000090, (void *)extab_dtor_801FEAB8
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_dtor_801FEB48 = {
    (void *)&dtor_801FEB48, 0x00000090, (void *)extab_dtor_801FEB48
};

/* --- asm function bodies (.text order = fn address order) --- */
asm void dtor_801FEA70(void) {
    nofralloc
    stwu r1, -0x10(r1)
    mflr r0
    stw r0, 0x14(r1)
    stw r31, 0xc(r1)
    mr. r31, r3
    beq dtor_801FEA70_L_801FEAA0
    lis r5, lbl_804EC1C8@ha
    extsh. r0, r4
    addi r0, r5, lbl_804EC1C8@l
    stw r0, 0x0(r31)
    ble dtor_801FEA70_L_801FEAA0
    bl dtor_8003AFB8
    dtor_801FEA70_L_801FEAA0:
    lwz r0, 0x14(r1)
    mr r3, r31
    lwz r31, 0xc(r1)
    mtlr r0
    addi r1, r1, 0x10
    blr
}

asm void dtor_801FEAB8(void) {
    nofralloc
    stwu r1, -0x30(r1)
    mflr r0
    stw r0, 0x34(r1)
    stw r31, 0x2c(r1)
    mr r31, r1
    stw r30, 0x28(r1)
    mr r30, r4
    stw r29, 0x24(r1)
    mr. r29, r3
    beq dtor_801FEAB8_L_801FEB10
    lwz r3, 0x0(r29)
    cmplwi r3, 0x0
    beq dtor_801FEAB8_L_801FEB00
    lwz r12, 0x0(r3)
    li r4, 0x1
    lwz r12, 0x8(r12)
    mtctr r12
    bctrl
    dtor_801FEAB8_L_801FEB00:
    extsh. r0, r30
    ble dtor_801FEAB8_L_801FEB10
    mr r3, r29
    bl dtor_8003AFB8
    dtor_801FEAB8_L_801FEB10:
    mr r3, r29
    b dtor_801FEAB8_L_801FEB24
    addi r3, r31, 0x8
    bl fn_8027248C
    dtor_801FEAB8_L_801FEB20:
    b dtor_801FEAB8_L_801FEB20
    dtor_801FEAB8_L_801FEB24:
    mr r10, r31
    lwz r31, 0x2c(r31)
    lwz r30, 0x28(r10)
    lwz r29, 0x24(r10)
    lwz r10, 0x0(r1)
    lwz r0, 0x4(r10)
    mr r1, r10
    mtlr r0
    blr
}

asm void dtor_801FEB48(void) {
    nofralloc
    stwu r1, -0x30(r1)
    mflr r0
    stw r0, 0x34(r1)
    stw r31, 0x2c(r1)
    mr r31, r1
    stw r30, 0x28(r1)
    mr r30, r4
    stw r29, 0x24(r1)
    mr. r29, r3
    beq dtor_801FEB48_L_801FEBA0
    lwz r3, 0x0(r29)
    cmplwi r3, 0x0
    beq dtor_801FEB48_L_801FEB90
    lwz r12, 0x0(r3)
    li r4, 0x1
    lwz r12, 0x8(r12)
    mtctr r12
    bctrl
    dtor_801FEB48_L_801FEB90:
    extsh. r0, r30
    ble dtor_801FEB48_L_801FEBA0
    mr r3, r29
    bl dtor_8003AFB8
    dtor_801FEB48_L_801FEBA0:
    mr r3, r29
    b dtor_801FEB48_L_801FEBB4
    addi r3, r31, 0x8
    bl fn_8027248C
    dtor_801FEB48_L_801FEBB0:
    b dtor_801FEB48_L_801FEBB0
    dtor_801FEB48_L_801FEBB4:
    mr r10, r31
    lwz r31, 0x2c(r31)
    lwz r30, 0x28(r10)
    lwz r29, 0x24(r10)
    lwz r10, 0x0(r1)
    lwz r0, 0x4(r10)
    mr r1, r10
    mtlr r0
    blr
}

