/*
 * dtk reversed-extab group `auto_fn_8002F640_text` bundle (1 TU, indivisible).
 * 6 functions sharing one extab group, all held as asm_fn with manually
 * emitted extab/extabindex via __declspec(section ".extab_user"/".extabindex_user").
 * tools/postprocess_extab_user.py renames sections + symbol names to the
 * `extab`/`extabindex` + `@etb_<addr>`/`@eti_<addr>` form dtk expects.
 *
 * Generated by `python tools/extract_fn_asm.py auto_fn_8002F640_text`.
 * Re-run to regenerate; hand edits below this header may be overwritten.
 *
 * See docs/per_fn_matching_strategy.md §12-13 and
 * docs/large_extab_group_strategy.md.
 */

/* === extracted from auto_fn_8002F640_text === */
/* Copy into the TU between forward decls and function bodies; */
/* keep emit order = target section layout (do not sort). */

/* --- extern decls: branch callees (bl/b targets) --- */
/* Open prototype (`extern void Foo();`) accepts any call signature; */
/* refine if the real prototype matters for header consumers. */
extern void DebugPrintf();
extern void MemoryHeap_GetStats();
extern void OSGetTick();
extern void MemoryManager_TimedFree();
extern void fn_801DB68C();
extern void fn_802554DC();
extern void fn_80293BBC();

/* --- extern decls: sda21-referenced data --- */
extern unsigned int SAFE;
extern unsigned int lbl_806CF010;
extern unsigned int lbl_806D0F9C;
extern unsigned int lbl_806D0FA4;
extern unsigned int lbl_806D0FA8;
extern unsigned int lbl_806D1880;
extern unsigned int lbl_806D2294;
extern unsigned int lbl_806D2298;
extern unsigned int lbl_806D22B4;
extern unsigned int lbl_806D22B8;

/* --- extern decls: large-data refs (@ha/@l pairs) --- */
/* Open array (`[]`) avoids sda21 strict-mode link errors when a future */
/* promote rewrites the asm_fn to C and references the symbol as `arr[i]`. */
extern unsigned int lbl_802E8F48[];
extern unsigned int lbl_802E9650[];
extern unsigned int lbl_80594080[];

/* --- forward decls --- */
asm void BootStateStruct_RefreshIfDue(void);
asm void HeapStats_DumpForTag(void);
asm void isJapanese(void);
asm void DebugLog_LvIdMsg(void);
asm void dtor_8002F910(void);
asm void dtor_8002F978(void);

/* --- extab (manual emit, .extab_user -> extab via objcopy) --- */
#pragma section R ".extab_user"
__declspec(section ".extab_user") static const unsigned char extab_dtor_8002F910[8] = {
    0x10, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_dtor_8002F978[8] = {
    0x08, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_fn_8002F640[8] = {
    0x08, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_HeapStats_DumpForTag[8] = {
    0x10, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
__declspec(section ".extab_user") static const unsigned char extab_fn_8002F8D4[8] = {
    0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

/* --- extabindex (manual emit, .extabindex_user -> extabindex via objcopy) --- */
#pragma section R ".extabindex_user"
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_fn_8002F640 = {
    (void *)&BootStateStruct_RefreshIfDue, 0x000001BC, (void *)extab_fn_8002F640
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_HeapStats_DumpForTag = {
    (void *)&HeapStats_DumpForTag, 0x000000D0, (void *)extab_HeapStats_DumpForTag
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_fn_8002F8D4 = {
    (void *)&DebugLog_LvIdMsg, 0x0000003C, (void *)extab_fn_8002F8D4
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_dtor_8002F910 = {
    (void *)&dtor_8002F910, 0x00000068, (void *)extab_dtor_8002F910
};
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_dtor_8002F978 = {
    (void *)&dtor_8002F978, 0x0000003C, (void *)extab_dtor_8002F978
};

/* --- asm function bodies (.text order = fn address order) --- */
asm void BootStateStruct_RefreshIfDue(void) {
    nofralloc
    stwu r1, -0x20(r1)
    mflr r0
    stw r0, 0x24(r1)
    stw r31, 0x1c(r1)
    lbz r0, lbl_806D0FA8(r13)
    extsb. r0, r0
    bne fn_8002F640_L_8002F66C
    li r3, 0x0
    li r0, 0x1
    stw r3, lbl_806D0FA4(r13)
    stb r0, lbl_806D0FA8(r13)
    fn_8002F640_L_8002F66C:
    lwz r31, lbl_806D0F9C(r13)
    bl OSGetTick
    lis r5, 0x8000
    lis r4, 0x431c
    lwz r5, 0xf8(r5)
    lis r0, 0x4330
    lwz r7, 0x0(r31)
    subi r6, r4, 0x217d
    srwi r4, r5, 2
    stw r0, 0x8(r1)
    mulhwu r0, r6, r4
    subf r3, r7, r3
    lfd f3, lbl_806D2298(r2)
    slwi r3, r3, 3
    lfs f1, lbl_806D2294(r2)
    lfs f0, SAFE(r2)
    srwi r0, r0, 15
    divwu r0, r3, r0
    stw r0, 0xc(r1)
    lfd f2, 0x8(r1)
    fsubs f2, f2, f3
    fdivs f1, f2, f1
    fcmpo cr0, f1, f0
    cror eq, gt, eq
    bne fn_8002F640_L_8002F6D8
    li r0, 0x1
    b fn_8002F640_L_8002F6DC
    fn_8002F640_L_8002F6D8:
    li r0, 0x0
    fn_8002F640_L_8002F6DC:
    clrlwi r0, r0, 24
    cmplwi r0, 0x1
    bne fn_8002F640_L_8002F7E8
    bl fn_802554DC
    bl fn_80293BBC
    lhz r0, 0x0(r3)
    lis r4, lbl_80594080@ha
    lwz r31, lbl_806D0F9C(r13)
    sthu r0, lbl_80594080@l(r4)
    lhz r0, 0x2(r3)
    sth r0, 0x2(r4)
    lhz r0, 0x4(r3)
    sth r0, 0x4(r4)
    lhz r0, 0x6(r3)
    sth r0, 0x6(r4)
    lwz r5, 0x8(r3)
    lwz r0, 0xc(r3)
    stw r5, 0x8(r4)
    stw r0, 0xc(r4)
    lbz r0, 0x10(r3)
    stb r0, 0x10(r4)
    lbz r0, 0x11(r3)
    stb r0, 0x11(r4)
    lhz r0, 0x12(r3)
    sth r0, 0x12(r4)
    lhz r0, 0x14(r3)
    sth r0, 0x14(r4)
    lhz r0, 0x16(r3)
    sth r0, 0x16(r4)
    lwz r5, 0x18(r3)
    lwz r0, 0x1c(r3)
    stw r5, 0x18(r4)
    stw r0, 0x1c(r4)
    lwz r5, 0x20(r3)
    lwz r0, 0x24(r3)
    stw r5, 0x20(r4)
    stw r0, 0x24(r4)
    lwz r0, 0x28(r3)
    stw r0, 0x28(r4)
    lwz r5, 0x2c(r3)
    lwz r0, 0x30(r3)
    stw r5, 0x2c(r4)
    stw r0, 0x30(r4)
    lwz r5, 0x34(r3)
    lwz r0, 0x38(r3)
    stw r5, 0x34(r4)
    stw r0, 0x38(r4)
    lwz r0, 0x3c(r3)
    stw r0, 0x3c(r4)
    lwz r5, 0x40(r3)
    lwz r0, 0x44(r3)
    stw r5, 0x40(r4)
    stw r0, 0x44(r4)
    lwz r5, 0x48(r3)
    lwz r0, 0x4c(r3)
    stw r5, 0x48(r4)
    stw r0, 0x4c(r4)
    lwz r5, 0x50(r3)
    lwz r0, 0x54(r3)
    stw r5, 0x50(r4)
    stw r0, 0x54(r4)
    lwz r0, 0x58(r3)
    stw r0, 0x58(r4)
    lwz r0, 0x5c(r3)
    stw r0, 0x5c(r4)
    bl OSGetTick
    stw r3, 0x0(r31)
    fn_8002F640_L_8002F7E8:
    lwz r0, 0x24(r1)
    lwz r31, 0x1c(r1)
    mtlr r0
    addi r1, r1, 0x20
    blr
}

asm void HeapStats_DumpForTag(void) {
    nofralloc
    stwu r1, -0x30(r1)
    mflr r0
    lis r4, lbl_802E8F48@ha
    stw r0, 0x34(r1)
    stw r31, 0x2c(r1)
    addi r31, r4, lbl_802E8F48@l
    stw r30, 0x28(r1)
    mr r30, r3
    addi r3, r31, 0x6ac
    crxor 6, 6, 6
    bl DebugPrintf
    lwz r3, lbl_806CF010(r13)
    addi r4, r1, 0x10
    addi r5, r1, 0xc
    addi r6, r1, 0x8
    bl MemoryHeap_GetStats
    lwz r3, 0x10(r1)
    lis r0, 0x4330
    stw r0, 0x18(r1)
    mr r5, r30
    srawi r0, r3, 10
    lfd f2, lbl_806D22B8(r2)
    addze r4, r0
    lwz r3, 0xc(r1)
    xoris r0, r4, 0x8000
    lfs f0, lbl_806D22B4(r2)
    stw r0, 0x1c(r1)
    srawi r0, r3, 10
    addze r0, r0
    addi r3, r31, 0x6d4
    lfd f1, 0x18(r1)
    stw r4, 0x10(r1)
    fsubs f1, f1, f2
    stw r0, 0xc(r1)
    fmuls f1, f1, f0
    creqv 6, 6, 6
    bl DebugPrintf
    lwz r4, 0xc(r1)
    addi r3, r31, 0x6ec
    crxor 6, 6, 6
    bl DebugPrintf
    lwz r4, 0x8(r1)
    addi r3, r31, 0x6fc
    crxor 6, 6, 6
    bl DebugPrintf
    lwz r0, 0x34(r1)
    li r3, 0x0
    lwz r31, 0x2c(r1)
    lwz r30, 0x28(r1)
    mtlr r0
    addi r1, r1, 0x30
    blr
}

asm void isJapanese(void) {
    nofralloc
    li r3, 0x0
    blr
}

asm void DebugLog_LvIdMsg(void) {
    nofralloc
    stwu r1, -0x10(r1)
    mflr r0
    lis r6, lbl_802E9650@ha
    stw r0, 0x14(r1)
    mr r0, r4
    mr r4, r3
    addi r3, r6, lbl_802E9650@l
    mr r6, r5
    mr r5, r0
    crxor 6, 6, 6
    bl DebugPrintf
    lwz r0, 0x14(r1)
    mtlr r0
    addi r1, r1, 0x10
    blr
}

asm void dtor_8002F910(void) {
    nofralloc
    stwu r1, -0x10(r1)
    mflr r0
    stw r0, 0x14(r1)
    stw r31, 0xc(r1)
    mr r31, r4
    stw r30, 0x8(r1)
    mr. r30, r3
    beq dtor_8002F910_L_8002F95C
    lwz r3, lbl_806D1880(r13)
    cmplwi r3, 0x0
    bne dtor_8002F910_L_8002F94C
    li r4, 0x1
    bl fn_801DB68C
    li r0, 0x0
    stw r0, lbl_806D1880(r13)
    dtor_8002F910_L_8002F94C:
    extsh. r0, r31
    ble dtor_8002F910_L_8002F95C
    mr r3, r30
    bl MemoryManager_TimedFree
    dtor_8002F910_L_8002F95C:
    lwz r0, 0x14(r1)
    mr r3, r30
    lwz r31, 0xc(r1)
    lwz r30, 0x8(r1)
    mtlr r0
    addi r1, r1, 0x10
    blr
}

asm void dtor_8002F978(void) {
    nofralloc
    stwu r1, -0x10(r1)
    mflr r0
    stw r0, 0x14(r1)
    stw r31, 0xc(r1)
    mr. r31, r3
    beq dtor_8002F978_L_8002F99C
    extsh. r0, r4
    ble dtor_8002F978_L_8002F99C
    bl MemoryManager_TimedFree
    dtor_8002F978_L_8002F99C:
    lwz r0, 0x14(r1)
    mr r3, r31
    lwz r31, 0xc(r1)
    mtlr r0
    addi r1, r1, 0x10
    blr
}

