/* LookupSin (0x80186928, size 0x38)
 *
 * 12-bit sin lookup. Takes a float (radians or unit-scaled angle), multiplies
 * by two sda2 floats to scale into a 12-bit table index, masks to 0..4095,
 * and returns the LUT float entry.
 *
 *     return lbl_80491988[((int)(lbl_806D9270 * (lbl_806D9274 * angle))) & 0xFFF];
 *
 * Singleton dtk reversed-extab group `auto_LookupSin_text`. Function has
 * extab/extabindex with Has-Elf-Vector / Large-Frame flags. Retreated to
 * asm_fn after 6 cycles (CW 1.3.2 schedules `stwu` first while target
 * interleaves `lfs`/`lis`/`lfs`/`addi`/`fmuls` before `stwu`; matches the
 * register-allocator-chase / micro-scheduling hard-block pattern documented
 * in per_fn_matching_strategy.md §14.3).
 *
 * Manual extab/extabindex emit via __declspec(section ".extab_user"/
 * ".extabindex_user"); tools/postprocess_extab_user.py renames to the dtk
 * canonical `extab`/`extabindex` + `@etb_<addr>`/`@eti_<addr>` symbols.
 *
 * Generated by `python tools/extract_fn_asm.py auto_LookupSin_text`.
 */

/* --- extern decls: sda21-referenced data --- */
extern unsigned int lbl_806D9270;
extern unsigned int lbl_806D9274;

/* --- extern decls: large-data refs (@ha/@l pairs) --- */
extern unsigned int lbl_80491988[];

/* --- forward decls --- */
asm void LookupSin(void);

/* --- extab (manual emit, .extab_user -> extab via objcopy) --- */
#pragma section R ".extab_user"
__declspec(section ".extab_user") static const unsigned char extab_LookupSin[8] = {
    0x00, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

/* --- extabindex (manual emit, .extabindex_user -> extabindex via objcopy) --- */
#pragma section R ".extabindex_user"
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_LookupSin = {
    (void *)&LookupSin, 0x00000038, (void *)extab_LookupSin
};

/* --- asm function bodies --- */
asm void LookupSin(void) {
    nofralloc
    lfs f0, lbl_806D9274(r2)
    lis r3, lbl_80491988@ha
    lfs f2, lbl_806D9270(r2)
    addi r3, r3, lbl_80491988@l
    fmuls f0, f0, f1
    stwu r1, -0x10(r1)
    fmuls f0, f2, f0
    fctiwz f0, f0
    stfd f0, 0x8(r1)
    lwz r0, 0xc(r1)
    clrlslwi r0, r0, 20, 2
    lfsx f1, r3, r0
    addi r1, r1, 0x10
    blr
}
