/* LookupCos (0x801868EC, size 0x3C)
 *
 * 12-bit cos lookup. Same LUT (lbl_80491988) and scale factors as LookupSin,
 * but with an additional phase-offset float (lbl_806D9290) folded into the
 * index calculation via fmadds. mkgp2 keeps sin/cos as separate symbols
 * sharing one LUT:
 *
 *     return lbl_80491988[((int)(lbl_806D9270 * (lbl_806D9274 * angle + lbl_806D9290))) & 0xFFF];
 *
 * Singleton dtk reversed-extab group `auto_LookupCos_text`. Function has
 * extab/extabindex with Has-Elf-Vector / Large-Frame flags. Sibling
 * LookupSin (0x80186928) hit the CW 1.3.2 micro-scheduling hard-block
 * (`stwu` slot vs interleaved `lfs`/`lis`/`addi`/`fmuls` pre-stack work,
 * section 14.3) after 6 cycles and was retreated to asm_fn -- LookupCos has the
 * same fingerprint plus an extra `fmadds`, so route to asm_fn directly
 * with semantics kept above for a future bundle promote pass.
 *
 * Manual extab/extabindex emit via __declspec(section ".extab_user"/
 * ".extabindex_user"); tools/postprocess_extab_user.py renames to the dtk
 * canonical `extab`/`extabindex` + `@etb_<addr>`/`@eti_<addr>` symbols.
 *
 * Generated by `python tools/extract_fn_asm.py auto_LookupCos_text`.
 */

/* --- extern decls: sda21-referenced data --- */
extern unsigned int lbl_806D9270;
extern unsigned int lbl_806D9274;
extern unsigned int lbl_806D9290;

/* --- extern decls: large-data refs (@ha/@l pairs) --- */
extern unsigned int lbl_80491988[];

/* --- forward decls --- */
asm void LookupCos(void);

/* --- extab (manual emit, .extab_user -> extab via objcopy) --- */
#pragma section R ".extab_user"
__declspec(section ".extab_user") static const unsigned char extab_LookupCos[8] = {
    0x00, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

/* --- extabindex (manual emit, .extabindex_user -> extabindex via objcopy) --- */
#pragma section R ".extabindex_user"
__declspec(section ".extabindex_user") static const struct { void *fn; unsigned int fn_size; void *extab; } extabindex_LookupCos = {
    (void *)&LookupCos, 0x0000003C, (void *)extab_LookupCos
};

/* --- asm function bodies --- */
asm void LookupCos(void) {
    nofralloc
    lfs f2, lbl_806D9274(r2)
    lis r3, lbl_80491988@ha
    lfs f0, lbl_806D9290(r2)
    addi r3, r3, lbl_80491988@l
    lfs f3, lbl_806D9270(r2)
    fmadds f0, f2, f1, f0
    stwu r1, -0x10(r1)
    fmuls f0, f3, f0
    fctiwz f0, f0
    stfd f0, 0x8(r1)
    lwz r0, 0xc(r1)
    clrlslwi r0, r0, 20, 2
    lfsx f1, r3, r0
    addi r1, r1, 0x10
    blr
}
