#!/usr/bin/env python3
"""Rank candidate "units" (struct/class clusters) for unit-first matching.

Read-only report. Ranking and metrics only — which unit to actually pick,
and how to batch it, stays a main-agent / human judgment call
(docs/unit_first_strategy.md, docs/orchestrator_ops.md L46-48).

Reads (all from project SoT, no .orchestrator/state.json required):
  - config/GNLJ82/symbols.txt        function names / addrs / sizes
  - config/GNLJ82/splits.txt         TU ranges (-> matched/nonmatching status)
  - configure.py                      Object(Matching|NonMatching, ...) flags
  - .orchestrator/extab_groups.json  (optional) extab bundle constraints;
                                      generated by tools/build_extab_map.py
                                      after a full ninja build

Usage:
  python tools/plan_units.py                 # ranking table (default top 30)
  python tools/plan_units.py --all           # every cluster
  python tools/plan_units.py --unit VfxSlot  # member listing for one unit
  python tools/plan_units.py --json          # machine-readable ranking

Metrics per cluster (prefix = first '_'-separated token of the fn name):
  runs      contiguous address runs the members occupy. 1 = the whole unit
            sits in one address range -> can become exactly one TU split.
  foreign   non-member functions inside the cluster's address span. They
            would have to join the TU (or force extra splits).
  ex>6      members whose extab group size exceeds 6 (escalation threshold,
            see docs/large_extab_group_strategy.md).
  ex_cross  extab groups that contain both member and non-member functions.
            Bundling constraint leaks outside the unit -> blocker.

A good first unit: runs=1, foreign=0, ex>6=0, ex_cross=0.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))

from init_orchestrator import (  # noqa: E402
    derive_status,
    is_placeholder_name,
    load_configure_objects,
    load_splits,
    load_symbols,
)

EXTAB_PATH = ROOT / ".orchestrator" / "extab_groups.json"

# Statuses that count as "part of the binary's function stream" when
# computing runs/foreign. Everything in symbols.txt with kind=function.
CLUSTER_STATUSES = ("pending", "matched", "asm_fn", "nonmatching")


def load_functions() -> dict[int, dict]:
    """SoT-derived function table: {addr: {name, section, size, status}}."""
    symbols = load_symbols()
    splits = load_splits()
    configure_objs = load_configure_objects()

    ranges: list[tuple[int, int, str]] = []
    for tu, sections in splits.items():
        for _sec, start, end in sections:
            ranges.append((start, end, tu))
    ranges.sort()

    def find_tu(addr: int) -> str | None:
        for start, end, tu in ranges:
            if start <= addr < end:
                return tu
        return None

    out: dict[int, dict] = {}
    for addr, sym in sorted(symbols.items()):
        if sym.get("kind") != "function":
            continue
        tu_hint = find_tu(addr)
        flag = configure_objs.get(tu_hint) if tu_hint else None
        status = derive_status(
            has_named_symbol=not is_placeholder_name(sym["name"]),
            tu_hint=tu_hint,
            matching_flag=flag,
        )
        out[addr] = {
            "name": sym["name"],
            "section": sym["section"],
            "size": sym.get("size") or 0,
            "status": status,
        }
    return out


def load_extab() -> tuple[dict[int, str], dict[str, list[int]]]:
    """(fn addr -> group name, group name -> member addrs). Empty if absent."""
    if not EXTAB_PATH.exists():
        return {}, {}
    data = json.loads(EXTAB_PATH.read_text(encoding="utf-8"))
    fn_to_group = {int(a, 16): g for a, g in data.get("fn_to_group", {}).items()}
    groups = {
        g: [int(a, 16) for a in info.get("function_addresses", [])]
        for g, info in data.get("groups", {}).items()
    }
    return fn_to_group, groups


def prefix_of(name: str) -> str:
    return name.split("_")[0]


def analyze_cluster(
    prefix: str,
    fns: dict[int, dict],
    fn_to_group: dict[int, str],
    groups: dict[str, list[int]],
) -> dict:
    members = sorted(
        (a, v) for a, v in fns.items() if prefix_of(v["name"]) == prefix
    )
    addrs = {a for a, _ in members}
    lo, hi = members[0][0], members[-1][0]

    runs = 0
    foreign = 0
    prev_in = False
    for a, v in sorted(fns.items()):
        if a < lo or a > hi:
            continue
        inside = a in addrs
        if inside and not prev_in:
            runs += 1
        if not inside:
            foreign += 1
        prev_in = inside

    status_counts: dict[str, int] = {}
    for _a, v in members:
        status_counts[v["status"]] = status_counts.get(v["status"], 0) + 1

    ex_big = 0
    ex_cross_groups: set[str] = set()
    ex_known = bool(fn_to_group)
    for a, _v in members:
        g = fn_to_group.get(a)
        if g is None:
            continue
        gsize = len(groups.get(g, []))
        if gsize > 6:
            ex_big += 1
        if any(m not in addrs for m in groups.get(g, [])):
            ex_cross_groups.add(g)

    pending_sizes = sorted(
        v["size"] for _a, v in members if v["status"] == "pending"
    )
    return {
        "prefix": prefix,
        "total": len(members),
        "pending": status_counts.get("pending", 0),
        "matched": status_counts.get("matched", 0),
        "asm_fn": status_counts.get("asm_fn", 0),
        "nonmatching": status_counts.get("nonmatching", 0),
        "span_lo": lo,
        "span_hi": hi,
        "runs": runs,
        "foreign": foreign,
        "extab_known": ex_known,
        "extab_big": ex_big,
        "extab_cross": len(ex_cross_groups),
        "pending_size": sum(pending_sizes),
        "pending_median": (
            pending_sizes[len(pending_sizes) // 2] if pending_sizes else 0
        ),
    }


def rank_key(c: dict) -> tuple:
    """Sort: cleanest unit first. Transparent, not a hidden judgment —
    blockers (extab leaks) sink, then fewer runs / less foreign / smaller
    pending median float up."""
    return (
        c["extab_cross"] > 0,
        c["extab_big"],
        c["runs"],
        min(c["foreign"], 50),
        c["pending_median"],
    )


def print_ranking(clusters: list[dict], limit: int | None) -> None:
    rows = sorted(clusters, key=rank_key)
    if limit:
        rows = rows[:limit]
    hdr = (
        f"{'unit':<22}{'pend':>5}{'done':>5}{'runs':>5}{'frgn':>6}"
        f"{'ex>6':>5}{'exX':>4}{'pend_B':>8}{'medB':>6}  span"
    )
    print(hdr)
    print("-" * len(hdr))
    for c in rows:
        done = c["matched"] + c["asm_fn"] + c["nonmatching"]
        ex_big = str(c["extab_big"]) if c["extab_known"] else "?"
        ex_cross = str(c["extab_cross"]) if c["extab_known"] else "?"
        print(
            f"{c['prefix']:<22}{c['pending']:>5}{done:>5}{c['runs']:>5}"
            f"{c['foreign']:>6}{ex_big:>5}{ex_cross:>4}"
            f"{c['pending_size']:>8}{c['pending_median']:>6}"
            f"  {c['span_lo']:08x}-{c['span_hi']:08x}"
        )
    if not any(c["extab_known"] for c in rows):
        print(
            "\nnote: .orchestrator/extab_groups.json not found -> extab "
            "columns unknown.\nRun `python configure.py && ninja "
            "build/GNLJ82/main.dol && python tools/build_extab_map.py` first."
        )


def print_unit(
    prefix: str,
    fns: dict[int, dict],
    fn_to_group: dict[int, str],
    groups: dict[str, list[int]],
) -> None:
    members = sorted(
        (a, v) for a, v in fns.items() if prefix_of(v["name"]) == prefix
    )
    if not members:
        sys.exit(f"no functions with prefix '{prefix}'")
    prev_end: int | None = None
    for a, v in members:
        gap = ""
        if prev_end is not None and a != prev_end:
            gap = f"  <gap {a - prev_end}B>"
        g = fn_to_group.get(a)
        gsize = len(groups.get(g, [])) if g else 1
        print(
            f"{a:08x} {v['size']:>5}B {v['status']:<12} extab_g={gsize:<3}"
            f" {v['name']}{gap}"
        )
        prev_end = a + v["size"]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--all", action="store_true", help="show every cluster")
    parser.add_argument("--limit", type=int, default=30,
                        help="ranking rows (default 30)")
    parser.add_argument("--min-fns", type=int, default=3,
                        help="min pending fns for a cluster to rank (default 3)")
    parser.add_argument("--unit", help="print member listing for one unit")
    parser.add_argument("--json", action="store_true",
                        help="ranking as JSON on stdout")
    args = parser.parse_args()

    fns = load_functions()
    fn_to_group, groups = load_extab()

    if args.unit:
        print_unit(args.unit, fns, fn_to_group, groups)
        return 0

    prefixes: dict[str, int] = {}
    for _a, v in fns.items():
        if v["status"] != "pending":
            continue
        if is_placeholder_name(v["name"]):
            continue
        p = prefix_of(v["name"])
        prefixes[p] = prefixes.get(p, 0) + 1

    clusters = [
        analyze_cluster(p, fns, fn_to_group, groups)
        for p, n in prefixes.items()
        if n >= args.min_fns
    ]
    if args.json:
        for c in clusters:
            c["span_lo"] = f"0x{c['span_lo']:08x}"
            c["span_hi"] = f"0x{c['span_hi']:08x}"
        print(json.dumps(sorted(clusters, key=rank_key), indent=2))
        return 0

    print_ranking(clusters, None if args.all else args.limit)
    return 0


if __name__ == "__main__":
    sys.exit(main())
